create temporary procedure sa_unload_define_option_defaults()
begin
    insert into sa_unload_option_default
        values( 'blocking','On' );
    insert into sa_unload_option_default
        values( 'blocking_timeout','0' );
    insert into sa_unload_option_default
        values( 'blocking_others_timeout','0' );
    insert into sa_unload_option_default
        values( 'checkpoint_time','60' );
    insert into sa_unload_option_default
        values( 'conversion_error','On' );
    insert into sa_unload_option_default
        values( 'date_format','YYYY-MM-DD' );
    insert into sa_unload_option_default
        values( 'date_order','YMD' );
    insert into sa_unload_option_default
        values( 'isolation_level','0' );
    insert into sa_unload_option_default
        values( 'updatable_statement_isolation','0' );
    insert into sa_unload_option_default
        values( 'lock_rejected_rows','Off' );
    insert into sa_unload_option_default
        values( 'login_procedure','sp_login_environment' );
    insert into sa_unload_option_default
        values( 'on_tsql_error','Conditional' );
    insert into sa_unload_option_default
        values( 'precision','30' );
    insert into sa_unload_option_default
        values( 'recovery_time','2' );
    insert into sa_unload_option_default
        values( 'replicate_all','Off' );
    insert into sa_unload_option_default
        values( 'row_counts','Off' );
    insert into sa_unload_option_default
        values( 'scale','6' );
    insert into sa_unload_option_default
        values( 'timestamp_format','YYYY-MM-DD HH:NN:SS.SSS' );
    insert into sa_unload_option_default
        values( 'timestamp_with_time_zone_format','YYYY-MM-DD HH:NN:SS.SSS+HH:NN' );
    insert into sa_unload_option_default
        values( 'time_format','HH:NN:SS.SSS' );
    insert into sa_unload_option_default
        values( 'wait_for_commit','Off' );
    insert into sa_unload_option_default
        values( 'quoted_identifier','On' );
    insert into sa_unload_option_default
        values( 'allow_nulls_by_default','On' );
    insert into sa_unload_option_default
        values( 'cooperative_commits','On' );
    insert into sa_unload_option_default
        values( 'cooperative_commit_timeout','250' );
    insert into sa_unload_option_default
        values( 'delayed_commits','Off' );
    insert into sa_unload_option_default
        values( 'delayed_commit_timeout','500' );
    insert into sa_unload_option_default
        values( 'non_keywords','' );
    insert into sa_unload_option_default
        values( 'reserved_keywords','' );
    insert into sa_unload_option_default
        values( 'sql_flagger_error_level','W' );
    insert into sa_unload_option_default
        values( 'sql_flagger_warning_level','W' );
    insert into sa_unload_option_default
        values( 'ansi_blanks','Off' );
    insert into sa_unload_option_default
        values( 'string_rtruncation','On' );
    insert into sa_unload_option_default
        values( 'divide_by_zero_error','On' );
    insert into sa_unload_option_default
        values( 'ansinull','On' );
    insert into sa_unload_option_default
        values( 'ansi_permissions','On' );
    insert into sa_unload_option_default
        values( 'close_on_endtrans','On' );
    insert into sa_unload_option_default
        values( 'tsql_variables','Off' );
    insert into sa_unload_option_default
        values( 'chained','On' );
    insert into sa_unload_option_default
        values( 'nearest_century','50' );
    insert into sa_unload_option_default
        values( 'fire_triggers','On' );
    insert into sa_unload_option_default
        values( 'background_priority','Off' );
    insert into sa_unload_option_default
        values( 'login_mode','Standard' );
    insert into sa_unload_option_default
        values( 'extern_login_credentials','Effective_user' );
    insert into sa_unload_option_default
        values( 'integrated_server_name','' );
    insert into sa_unload_option_default
        values( 'connection_authentication','' );
    insert into sa_unload_option_default
        values( 'auto_commit','Off' );
    insert into sa_unload_option_default
        values( 'java_main_userid','' );
    insert into sa_unload_option_default
        values( 'java_location','' );
    insert into sa_unload_option_default
        values( 'java_vm_options','' );
    insert into sa_unload_option_default
        values( 'java_class_path','' );
    insert into sa_unload_option_default
        values( 'suppress_tds_debugging','Off' );
    insert into sa_unload_option_default
        values( 'upgrade_database_capability','' );
    insert into sa_unload_option_default
        values( 'database_authentication','' );
    insert into sa_unload_option_default
        values( 'default_timestamp_increment','1' );
    insert into sa_unload_option_default
        values( 'escape_character','On' );
    insert into sa_unload_option_default
        values( 'prefetch','Conditional' );
    insert into sa_unload_option_default
        values( 'continue_after_raiserror','On' );
    insert into sa_unload_option_default
        values( 'cis_option','0' );
    insert into sa_unload_option_default
        values( 'cis_rowset_size','50' );
    insert into sa_unload_option_default
        values( 'ansi_close_cursors_on_rollback','Off' );
    insert into sa_unload_option_default
        values( 'max_statement_count','50' );
    insert into sa_unload_option_default
        values( 'max_cursor_count','50' );
    insert into sa_unload_option_default
        values( 'min_password_length','6' );
    insert into sa_unload_option_default
        values( 'auditing','Off' );
    insert into sa_unload_option_default
        values( 'conn_auditing','On' );
    insert into sa_unload_option_default
        values( 'auditing_options','4294967295' );
    insert into sa_unload_option_default
        values( 'tds_empty_string_is_null','Off' );
    insert into sa_unload_option_default
        values( 'optimization_level','9' );
    insert into sa_unload_option_default
        values( 'extended_join_syntax','On' );
    insert into sa_unload_option_default
        values( 'ansi_update_constraints','Cursors' );
    insert into sa_unload_option_default
        values( 'optimization_goal','All-rows' );
    insert into sa_unload_option_default
        values( 'global_database_id','2147483647' );
    insert into sa_unload_option_default
        values( 'max_hash_size','10' );
    insert into sa_unload_option_default
        values( 'prevent_article_pkey_update','On' );
    insert into sa_unload_option_default
        values( 'truncate_timestamp_values','Off' );
    insert into sa_unload_option_default
        values( 'return_date_time_as_string','Off' );
    insert into sa_unload_option_default
        values( 'first_day_of_week','7' );
    insert into sa_unload_option_default
        values( 'preserve_source_format','On' );
    insert into sa_unload_option_default
        values( 'time_zone_adjustment','0' );
    insert into sa_unload_option_default
        values( 'exclude_operators','' );
    insert into sa_unload_option_default
        values( 'user_estimates','Override-magic' );
    insert into sa_unload_option_default
        values( 'max_plans_cached','20' );
    insert into sa_unload_option_default
        values( 'sort_collation','Internal' );
    insert into sa_unload_option_default
        values( 'pinned_cursor_percent_of_cache','10' );
    insert into sa_unload_option_default
        values( 'on_charset_conversion_failure','Ignore' );
    insert into sa_unload_option_default
        values( 'update_statistics','On' );
    insert into sa_unload_option_default
        values( 'collect_statistics_on_dml_updates','On' );
    insert into sa_unload_option_default
        values( 'max_recursive_iterations','100' );
    insert into sa_unload_option_default
        values( 'max_query_tasks','0' );
    insert into sa_unload_option_default
        values( 'max_parallel_statements','0' );
    insert into sa_unload_option_default
        values( 'for_xml_null_treatment','Omit' );
    insert into sa_unload_option_default
        values( 'subsume_row_locks','On' );
    insert into sa_unload_option_default
        values( 'read_past_deleted','On' );
    insert into sa_unload_option_default
        values( 'temp_space_limit_check','On' );
    insert into sa_unload_option_default
        values( 'force_view_creation','Off' );
    insert into sa_unload_option_default
        values( 'dedicated_task','Off' );
    insert into sa_unload_option_default
        values( 'debug_messages','Off' );
    insert into sa_unload_option_default
        values( 'optimization_workload','Mixed' );
    insert into sa_unload_option_default
        values( 'odbc_distinguish_char_and_varchar','Off' );
    insert into sa_unload_option_default
        values( 'remote_idle_timeout','15' );
    insert into sa_unload_option_default
        values( 'ansi_substring','On' );
    insert into sa_unload_option_default
        values( 'odbc_describe_binary_as_varbinary','Off' );
    insert into sa_unload_option_default
        values( 'rollback_on_deadlock','On' );
    insert into sa_unload_option_default
        values( 'log_deadlocks','Off' );
    insert into sa_unload_option_default
        values( 'webservice_namespace_host','' );
    insert into sa_unload_option_default
        values( 'webservice_sessionid_name','SessionID' );
    insert into sa_unload_option_default
        values( 'http_session_timeout','30' );
    insert into sa_unload_option_default
        values( 'http_connection_pool_basesize','10' );
    insert into sa_unload_option_default
        values( 'http_connection_pool_timeout','60' );
    insert into sa_unload_option_default
        values( 'request_timeout','0' );
    insert into sa_unload_option_default
        values( 'synchronize_mirror_on_commit','Off' );
    insert into sa_unload_option_default
        values( 'uuid_has_hyphens','On' );
    insert into sa_unload_option_default
        values( 'verify_password_function','' );
    insert into sa_unload_option_default
        values( 'allow_snapshot_isolation','Off' );
    insert into sa_unload_option_default
        values( 'default_dbspace','' );
    insert into sa_unload_option_default
        values( 'oem_string','' );
    insert into sa_unload_option_default
        values( 'max_temp_space','0' );
    insert into sa_unload_option_default
        values( 'secure_feature_key','' );
    insert into sa_unload_option_default
        values( 'materialized_view_optimization','Stale' );
    insert into sa_unload_option_default
        values( 'tsql_outer_joins','Off' );
    insert into sa_unload_option_default
        values( 'post_login_procedure','dbo.sa_post_login_procedure' );
    insert into sa_unload_option_default
        values( 'max_client_statements_cached','10' );
    insert into sa_unload_option_default
        values( 'query_mem_timeout','-1' );
    insert into sa_unload_option_default
        values( 'allow_read_client_file','Off' );
    insert into sa_unload_option_default
        values( 'allow_write_client_file','Off' );
    insert into sa_unload_option_default
        values( 'priority','normal' );
    insert into sa_unload_option_default
        values( 'max_priority','normal' );
    insert into sa_unload_option_default
        values( 'progress_messages','Off' );
    insert into sa_unload_option_default
        values( 'st_geometry_describe_type','CHAR' );
    insert into sa_unload_option_default
        values( 'st_geometry_astext_format','WKT' );
    insert into sa_unload_option_default
        values( 'st_geometry_asbinary_format','WKB' );
    insert into sa_unload_option_default
        values( 'st_geometry_asxml_format','GML' );
    insert into sa_unload_option_default
        values( 'st_geometry_on_invalid','Error' );
    insert into sa_unload_option_default
        values( 'st_geometry_interpolation','relative-tolerance-percent=.3' );
    insert into sa_unload_option_default
        values( 'min_role_admins','1' );
    insert into sa_unload_option_default
        values( 'trusted_certificates_file','' );
    insert into sa_unload_option_default
        values( 'db_publisher','-1' );
    insert into sa_unload_option_default
        values( 'auto_commit_on_create_local_temp_index','Off' );
    insert into sa_unload_option_default
        values( 'disk_sandbox','Off' );
    insert into sa_unload_option_default
        values( 'audit_log','' );
    insert into sa_unload_option_default
        values( 'max_connections','32766' );
    insert into sa_unload_option_default
        values( 'time_zone','' );
    insert into sa_unload_option_default
        values( 'connection_type','Standard' );
    insert into sa_unload_option_default
        values( 'parameterization_level','Off' );
    insert into sa_unload_option_default
        values( 'reserved_connections','0' );
    insert into sa_unload_option_default
        values( 'verify_all_columns','Off' );
    insert into sa_unload_option_default
        values( 'delete_old_logs','Off' );
    insert into sa_unload_option_default
        values( 'qualify_owners','On' );
    insert into sa_unload_option_default
        values( 'quote_all_identifiers','Off' );
    insert into sa_unload_option_default
        values( 'replication_error','' );
    insert into sa_unload_option_default
        values( 'replication_error_piece','' );
    insert into sa_unload_option_default
        values( 'subscribe_by_remote','On' );
    insert into sa_unload_option_default
        values( 'verify_threshold','1000' );
    insert into sa_unload_option_default
        values( 'blob_threshold','256' );
    insert into sa_unload_option_default
        values( 'compression','6' );
    insert into sa_unload_option_default
        values( 'external_remote_options','Off' );
    insert into sa_unload_option_default
        values( 'save_remote_passwords','On' );
    insert into sa_unload_option_default
        values( 'sr_date_format','yyyy/mm/dd' );
    insert into sa_unload_option_default
        values( 'sr_time_format','hh:nn:ss.Ssssss' );
    insert into sa_unload_option_default
        values( 'sr_timestamp_format','yyyy/mm/dd hh:nn:ss.Ssssss' );
    insert into sa_unload_option_default
        values( 'sr_timestamp_with_time_zone_format','yyyy/mm/dd hh:nn:ss.Ssssss +hh:nn' );
    insert into sa_unload_option_default
        values( 'assume_distinct_servers','Off' );
    insert into sa_unload_option_default
        values( 'ml_remote_id','' );
    delete from sa_unload_option_default
       where optname = 'preserve_source_format'; 
end
go
