#!/bin/bash

# In case we are being run from another service, set some stock paths

PATH="/bin:/sbin:/usr/bin:/usr/sbin:/opt/usr/bin:/opt/usr/sbin:/usr/local/bin:/usr/local/sbin"

if [ "${1:-}" = "-y" ]; then
    RESPONSE=y
else
    echo "Files will be deleted.  Are you sure? (N/y)"
    read RESPONSE
fi
[ "${RESPONSE:-}" != "y" ] && [ "${RESPONSE:-}" != "Y" ] && exit

OPWD=$PWD
cd "`dirname "$0"`"
SAROOT=$PWD
[ -r bin32/sadoc ] && bin32/sadoc -stop >/dev/null 2>&1
[ -r bin64/sadoc ] && bin64/sadoc -stop >/dev/null 2>&1
rm -f SAP_SQL_Anywhere_version.txt
rm -f bin32/.scRepository*
rm -f bin32/createcert
rm -f bin32/createkey
rm -f bin32/dbbackup
rm -f bin32/dbdsn
rm -f bin32/dbeng17
rm -f bin32/dbeng17.lic
rm -f bin32/dberase
rm -f bin32/dbexternc17
rm -f bin32/dbfhide
rm -f bin32/dbinfo
rm -f bin32/dbinit
rm -f bin32/dbisql
rm -f bin32/dbisql_32.rep
rm -f bin32/dbisqlc
rm -f bin32/dblic
rm -f bin32/dblocate
rm -f bin32/dblog
rm -f bin32/dbmanageetd
rm -f bin32/dbmlsync
rm -f bin32/dbns17
rm -f bin32/dbping
rm -f bin32/dbprof
rm -f bin32/dbremote
rm -f bin32/dbspawn
rm -f bin32/dbsrv17
rm -f bin32/dbsrv17.lic
rm -f bin32/dbstats
rm -f bin32/dbstop
rm -f bin32/dbsupport
rm -f bin32/dbsvc
rm -f bin32/dbsvc_scripts/dbsvc_iface
rm -f bin32/dbsvc_scripts/dbsvc_iface_lsb
rm -f bin32/dbsvc_scripts/dbsvc_iface_rh
rm -f bin32/dbsvc_scripts/dbsvc_iface_suse
rm -f bin32/dbsvc_scripts/dbsvc_iface_systemd
rm -f bin32/dbsvc_scripts/distro.sh
rm -f bin32/dbsvc_scripts/svc_functions
rm -f bin32/dbsvc_scripts/svc_t_dbeng
rm -f bin32/dbsvc_scripts/svc_t_dbmlsync
rm -f bin32/dbsvc_scripts/svc_t_dbns
rm -f bin32/dbsvc_scripts/svc_t_dbremote
rm -f bin32/dbsvc_scripts/svc_t_dbsrv
rm -f bin32/dbsvc_scripts/svc_t_network
rm -f bin32/dbsvc_scripts/svc_t_personal
rm -f bin32/dbsvc_scripts/svc_t_standalone
rm -f bin32/dbsvc_scripts/utility.sh
rm -f bin32/dbtran
rm -f bin32/dbtsinfo
rm -f bin32/dbunload
rm -f bin32/dbunlspt
rm -f bin32/dbupgrad
rm -f bin32/dbvalid
rm -f bin32/dbversion
rm -f bin32/dbxtract
rm -f bin32/htmlview
rm -f bin32/jsenv.js
rm -f bin32/language/de/messages.txt
rm -f bin32/language/de/usage.txt
rm -f bin32/language/en/messages.txt
rm -f bin32/language/en/usage.txt
rm -f bin32/language/fr/messages.txt
rm -f bin32/language/fr/usage.txt
rm -f bin32/language/ja/messages.txt
rm -f bin32/language/ja/usage.txt
rm -f bin32/language/zh/messages.txt
rm -f bin32/language/zh/usage.txt
rm -f bin32/mlfiletransfer
rm -f bin32/mlsrv17.lic
rm -f bin32/mltemplate
rm -f bin32/newdemo.sh
rm -f bin32/perlenv.pl
rm -f bin32/phpenv.php
rm -f bin32/run_migrator.sh
rm -f bin32/sa_config.csh
rm -f bin32/sa_config.sh
rm -f bin32/samonitor
rm -f bin32/samonitor.sh
rm -f bin32/samonitor.template
rm -f bin32/scjview
rm -f bin32/smstart.dat
rm -f bin32/smstop.dat
rm -f bin32/sqlpp
rm -f bin32/uldeploy
rm -f bin32/uleng17
rm -f bin32/ulerase
rm -f bin32/ulinfo
rm -f bin32/ulinit
rm -f bin32/ulload
rm -f bin32/ulstop
rm -f bin32/ulsync
rm -f bin32/ulunload
rm -f bin32/ulvalid
rm -f bin32/usm.xsd
rm -f bin32/viewcert
rm -f bin32s/createcert
rm -f bin32s/createkey
rm -f bin32s/dbbackup
rm -f bin32s/dbdsn
rm -f bin32s/dbeng17
rm -f bin32s/dberase
rm -f bin32s/dbexternc17
rm -f bin32s/dbfhide
rm -f bin32s/dbinfo
rm -f bin32s/dbinit
rm -f bin32s/dbisql
rm -f bin32s/dbisqlc
rm -f bin32s/dblic
rm -f bin32s/dblocate
rm -f bin32s/dblog
rm -f bin32s/dbmanageetd
rm -f bin32s/dbmlsync
rm -f bin32s/dbns17
rm -f bin32s/dbping
rm -f bin32s/dbprof
rm -f bin32s/dbremote
rm -f bin32s/dbspawn
rm -f bin32s/dbsrv17
rm -f bin32s/dbstats
rm -f bin32s/dbstop
rm -f bin32s/dbsupport
rm -f bin32s/dbsvc
rm -f bin32s/dbsvc_scripts/dbsvc_iface
rm -f bin32s/dbsvc_scripts/dbsvc_iface_lsb
rm -f bin32s/dbsvc_scripts/dbsvc_iface_rh
rm -f bin32s/dbsvc_scripts/dbsvc_iface_suse
rm -f bin32s/dbsvc_scripts/dbsvc_iface_systemd
rm -f bin32s/dbsvc_scripts/distro.sh
rm -f bin32s/dbsvc_scripts/svc_functions
rm -f bin32s/dbsvc_scripts/svc_t_dbeng
rm -f bin32s/dbsvc_scripts/svc_t_dbmlsync
rm -f bin32s/dbsvc_scripts/svc_t_dbns
rm -f bin32s/dbsvc_scripts/svc_t_dbremote
rm -f bin32s/dbsvc_scripts/svc_t_dbsrv
rm -f bin32s/dbsvc_scripts/svc_t_network
rm -f bin32s/dbsvc_scripts/svc_t_personal
rm -f bin32s/dbsvc_scripts/svc_t_standalone
rm -f bin32s/dbsvc_scripts/utility.sh
rm -f bin32s/dbtran
rm -f bin32s/dbtsinfo
rm -f bin32s/dbunload
rm -f bin32s/dbunlspt
rm -f bin32s/dbupgrad
rm -f bin32s/dbvalid
rm -f bin32s/dbversion
rm -f bin32s/dbxtract
rm -f bin32s/htmlview
rm -f bin32s/jsenv.js
rm -f bin32s/language/de/messages.txt
rm -f bin32s/language/de/usage.txt
rm -f bin32s/language/en/messages.txt
rm -f bin32s/language/en/usage.txt
rm -f bin32s/language/fr/messages.txt
rm -f bin32s/language/fr/usage.txt
rm -f bin32s/language/ja/messages.txt
rm -f bin32s/language/ja/usage.txt
rm -f bin32s/language/zh/messages.txt
rm -f bin32s/language/zh/usage.txt
rm -f bin32s/mlfiletransfer
rm -f bin32s/mltemplate
rm -f bin32s/newdemo.sh
rm -f bin32s/perlenv.pl
rm -f bin32s/phpenv.php
rm -f bin32s/run_migrator.sh
rm -f bin32s/samonitor
rm -f bin32s/samonitor.sh
rm -f bin32s/samonitor.template
rm -f bin32s/scjview
rm -f bin32s/smstop.dat
rm -f bin32s/sqlpp
rm -f bin32s/uldeploy
rm -f bin32s/uleng17
rm -f bin32s/ulerase
rm -f bin32s/ulinfo
rm -f bin32s/ulinit
rm -f bin32s/ulload
rm -f bin32s/ulstop
rm -f bin32s/ulsync
rm -f bin32s/ulunload
rm -f bin32s/ulvalid
rm -f bin32s/usm.xsd
rm -f bin32s/viewcert
rm -f bin64/.scRepository*
rm -f bin64/createcert
rm -f bin64/createkey
rm -f bin64/dbbackup
rm -f bin64/dbdsn
rm -f bin64/dbeng17
rm -f bin64/dbeng17.lic
rm -f bin64/dberase
rm -f bin64/dbexternc17
rm -f bin64/dbfhide
rm -f bin64/dbinfo
rm -f bin64/dbinit
rm -f bin64/dbisql
rm -f bin64/dbisql_64.rep
rm -f bin64/dbisqlc
rm -f bin64/dblic
rm -f bin64/dblocate
rm -f bin64/dblog
rm -f bin64/dbmanageetd
rm -f bin64/dbmlsync
rm -f bin64/dbns17
rm -f bin64/dbping
rm -f bin64/dbprof
rm -f bin64/dbremote
rm -f bin64/dbspawn
rm -f bin64/dbsrv17
rm -f bin64/dbsrv17.lic
rm -f bin64/dbstats
rm -f bin64/dbstop
rm -f bin64/dbsupport
rm -f bin64/dbsvc
rm -f bin64/dbsvc_scripts/dbsvc_iface
rm -f bin64/dbsvc_scripts/dbsvc_iface_lsb
rm -f bin64/dbsvc_scripts/dbsvc_iface_rh
rm -f bin64/dbsvc_scripts/dbsvc_iface_suse
rm -f bin64/dbsvc_scripts/dbsvc_iface_systemd
rm -f bin64/dbsvc_scripts/distro.sh
rm -f bin64/dbsvc_scripts/svc_functions
rm -f bin64/dbsvc_scripts/svc_t_dbeng
rm -f bin64/dbsvc_scripts/svc_t_dbmlsync
rm -f bin64/dbsvc_scripts/svc_t_dbns
rm -f bin64/dbsvc_scripts/svc_t_dbremote
rm -f bin64/dbsvc_scripts/svc_t_dbsrv
rm -f bin64/dbsvc_scripts/svc_t_mlsrv
rm -f bin64/dbsvc_scripts/svc_t_mlsync
rm -f bin64/dbsvc_scripts/svc_t_mobilink
rm -f bin64/dbsvc_scripts/svc_t_network
rm -f bin64/dbsvc_scripts/svc_t_personal
rm -f bin64/dbsvc_scripts/svc_t_rshost
rm -f bin64/dbsvc_scripts/svc_t_rsoe
rm -f bin64/dbsvc_scripts/svc_t_standalone
rm -f bin64/dbsvc_scripts/utility.sh
rm -f bin64/dbtran
rm -f bin64/dbtsinfo
rm -f bin64/dbunload
rm -f bin64/dbunlspt
rm -f bin64/dbupgrad
rm -f bin64/dbvalid
rm -f bin64/dbversion
rm -f bin64/dbxtract
rm -f bin64/htmlview
rm -f bin64/jre180/.hotspot_compiler
rm -f bin64/jre180/COPYRIGHT
rm -f bin64/jre180/THIRDPARTYLICENSEREADME.txt
rm -f bin64/jre180/Welcome.html
rm -f bin64/jre180/bin/forkhelper
rm -f bin64/jre180/bin/java
rm -f bin64/jre180/bin/jjs
rm -f bin64/jre180/bin/jvmmon
rm -f bin64/jre180/bin/jvmmond
rm -f bin64/jre180/bin/jvmprof
rm -f bin64/jre180/bin/keytool
rm -f bin64/jre180/bin/orbd
rm -f bin64/jre180/bin/pack200
rm -f bin64/jre180/bin/policytool
rm -f bin64/jre180/bin/rmid
rm -f bin64/jre180/bin/rmiregistry
rm -f bin64/jre180/bin/servertool
rm -f bin64/jre180/bin/tnameserv
rm -f bin64/jre180/bin/unpack200
rm -f bin64/jre180/buildinfo.txt
rm -f bin64/jre180/lib/add_sapjvm_alternatives.sh
rm -f bin64/jre180/lib/amd64/jli/libjli.so
rm -f bin64/jre180/lib/amd64/jvm.cfg
rm -f bin64/jre180/lib/amd64/libattach.so
rm -f bin64/jre180/lib/amd64/libawt.so
rm -f bin64/jre180/lib/amd64/libawt_headless.so
rm -f bin64/jre180/lib/amd64/libawt_xawt.so
rm -f bin64/jre180/lib/amd64/libdcpr.so
rm -f bin64/jre180/lib/amd64/libdt_socket.so
rm -f bin64/jre180/lib/amd64/libfontmanager.so
rm -f bin64/jre180/lib/amd64/libhprof.so
rm -f bin64/jre180/lib/amd64/libinstrument.so
rm -f bin64/jre180/lib/amd64/libj2gss.so
rm -f bin64/jre180/lib/amd64/libj2pcsc.so
rm -f bin64/jre180/lib/amd64/libj2pkcs11.so
rm -f bin64/jre180/lib/amd64/libjaas_unix.so
rm -f bin64/jre180/lib/amd64/libjava.so
rm -f bin64/jre180/lib/amd64/libjava_crw_demo.so
rm -f bin64/jre180/lib/amd64/libjawt.so
rm -f bin64/jre180/lib/amd64/libjdwp.so
rm -f bin64/jre180/lib/amd64/libjpeg.so
rm -f bin64/jre180/lib/amd64/libjsdt.so
rm -f bin64/jre180/lib/amd64/libjsig.so
rm -f bin64/jre180/lib/amd64/libjsound.so
rm -f bin64/jre180/lib/amd64/libkcms.so
rm -f bin64/jre180/lib/amd64/liblcms.so
rm -f bin64/jre180/lib/amd64/libmanagement.so
rm -f bin64/jre180/lib/amd64/libmlib_image.so
rm -f bin64/jre180/lib/amd64/libnet.so
rm -f bin64/jre180/lib/amd64/libnio.so
rm -f bin64/jre180/lib/amd64/libnpt.so
rm -f bin64/jre180/lib/amd64/libsapext.so
rm -f bin64/jre180/lib/amd64/libsapjvm_inspector.so
rm -f bin64/jre180/lib/amd64/libsapmanagement.so
rm -f bin64/jre180/lib/amd64/libsaproc.so
rm -f bin64/jre180/lib/amd64/libsapsession.so
rm -f bin64/jre180/lib/amd64/libsctp.so
rm -f bin64/jre180/lib/amd64/libsplashscreen.so
rm -f bin64/jre180/lib/amd64/libsunec.so
rm -f bin64/jre180/lib/amd64/libt2k.so
rm -f bin64/jre180/lib/amd64/libunpack.so
rm -f bin64/jre180/lib/amd64/libverify.so
rm -f bin64/jre180/lib/amd64/libzip.so
rm -f bin64/jre180/lib/amd64/server/Xusage.txt
rm -f bin64/jre180/lib/amd64/server/libjsig.so
rm -f bin64/jre180/lib/amd64/server/libjvm.so
rm -f bin64/jre180/lib/amd64/server/sapjvm.info
rm -f bin64/jre180/lib/calendars.properties
rm -f bin64/jre180/lib/charsets.jar
rm -f bin64/jre180/lib/classlist
rm -f bin64/jre180/lib/cmm/CIEXYZ.pf
rm -f bin64/jre180/lib/cmm/GRAY.pf
rm -f bin64/jre180/lib/cmm/LINEAR_RGB.pf
rm -f bin64/jre180/lib/cmm/PYCC.pf
rm -f bin64/jre180/lib/cmm/sRGB.pf
rm -f bin64/jre180/lib/content-types.properties
rm -f bin64/jre180/lib/currency.data
rm -f bin64/jre180/lib/ext/cldrdata.jar
rm -f bin64/jre180/lib/ext/dnsns.jar
rm -f bin64/jre180/lib/ext/jaccess.jar
rm -f bin64/jre180/lib/ext/localedata.jar
rm -f bin64/jre180/lib/ext/meta-index
rm -f bin64/jre180/lib/ext/nashorn.jar
rm -f bin64/jre180/lib/ext/sunec.jar
rm -f bin64/jre180/lib/ext/sunjce_provider.jar
rm -f bin64/jre180/lib/ext/sunpkcs11.jar
rm -f bin64/jre180/lib/ext/zipfs.jar
rm -f bin64/jre180/lib/flavormap.properties
rm -f bin64/jre180/lib/fontconfig.RedHat.5.bfc
rm -f bin64/jre180/lib/fontconfig.RedHat.5.properties.src
rm -f bin64/jre180/lib/fontconfig.RedHat.6.bfc
rm -f bin64/jre180/lib/fontconfig.RedHat.6.properties.src
rm -f bin64/jre180/lib/fontconfig.SuSE.10.bfc
rm -f bin64/jre180/lib/fontconfig.SuSE.10.properties.src
rm -f bin64/jre180/lib/fontconfig.SuSE.11.bfc
rm -f bin64/jre180/lib/fontconfig.SuSE.11.properties.src
rm -f bin64/jre180/lib/fontconfig.Turbo.bfc
rm -f bin64/jre180/lib/fontconfig.Turbo.properties.src
rm -f bin64/jre180/lib/fontconfig.bfc
rm -f bin64/jre180/lib/fontconfig.properties.src
rm -f bin64/jre180/lib/fonts/LucidaBrightDemiBold.ttf
rm -f bin64/jre180/lib/fonts/LucidaBrightDemiItalic.ttf
rm -f bin64/jre180/lib/fonts/LucidaBrightItalic.ttf
rm -f bin64/jre180/lib/fonts/LucidaBrightRegular.ttf
rm -f bin64/jre180/lib/fonts/LucidaSansDemiBold.ttf
rm -f bin64/jre180/lib/fonts/LucidaSansRegular.ttf
rm -f bin64/jre180/lib/fonts/LucidaTypewriterBold.ttf
rm -f bin64/jre180/lib/fonts/LucidaTypewriterRegular.ttf
rm -f bin64/jre180/lib/fonts/fonts.dir
rm -f bin64/jre180/lib/hijrah-config-umalqura.properties
rm -f bin64/jre180/lib/images/cursors/cursors.properties
rm -f bin64/jre180/lib/images/cursors/invalid32x32.gif
rm -f bin64/jre180/lib/images/cursors/motif_CopyDrop32x32.gif
rm -f bin64/jre180/lib/images/cursors/motif_CopyNoDrop32x32.gif
rm -f bin64/jre180/lib/images/cursors/motif_LinkDrop32x32.gif
rm -f bin64/jre180/lib/images/cursors/motif_LinkNoDrop32x32.gif
rm -f bin64/jre180/lib/images/cursors/motif_MoveDrop32x32.gif
rm -f bin64/jre180/lib/images/cursors/motif_MoveNoDrop32x32.gif
rm -f bin64/jre180/lib/jce.jar
rm -f bin64/jre180/lib/jexec
rm -f bin64/jre180/lib/jsse.jar
rm -f bin64/jre180/lib/jvm.hprof.txt
rm -f bin64/jre180/lib/logging.properties
rm -f bin64/jre180/lib/management-agent.jar
rm -f bin64/jre180/lib/management/jmxremote.access
rm -f bin64/jre180/lib/management/jmxremote.password.template
rm -f bin64/jre180/lib/management/management.properties
rm -f bin64/jre180/lib/management/snmp.acl.template
rm -f bin64/jre180/lib/meta-index
rm -f bin64/jre180/lib/net.properties
rm -f bin64/jre180/lib/oblique-fonts/LucidaSansDemiOblique.ttf
rm -f bin64/jre180/lib/oblique-fonts/LucidaSansOblique.ttf
rm -f bin64/jre180/lib/oblique-fonts/LucidaTypewriterBoldOblique.ttf
rm -f bin64/jre180/lib/oblique-fonts/LucidaTypewriterOblique.ttf
rm -f bin64/jre180/lib/oblique-fonts/fonts.dir
rm -f bin64/jre180/lib/psfont.properties.ja
rm -f bin64/jre180/lib/psfontj2d.properties
rm -f bin64/jre180/lib/remove_sapjvm_alternatives.sh
rm -f bin64/jre180/lib/resources.jar
rm -f bin64/jre180/lib/rt.jar
rm -f bin64/jre180/lib/sapjvm-tools.jar
rm -f bin64/jre180/lib/security/blacklist
rm -f bin64/jre180/lib/security/blacklisted.certs
rm -f bin64/jre180/lib/security/cacerts
rm -f bin64/jre180/lib/security/java.policy
rm -f bin64/jre180/lib/security/java.security
rm -f bin64/jre180/lib/security/policy/limited/US_export_policy.jar
rm -f bin64/jre180/lib/security/policy/limited/local_policy.jar
rm -f bin64/jre180/lib/security/policy/unlimited/US_export_policy.jar
rm -f bin64/jre180/lib/security/policy/unlimited/local_policy.jar
rm -f bin64/jre180/lib/security/trusted.libraries
rm -f bin64/jre180/lib/sound.properties
rm -f bin64/jre180/lib/src_ecc.zip
rm -f bin64/jre180/lib/tzdb.dat
rm -f bin64/jsenv.js
rm -f bin64/language/de/messages.txt
rm -f bin64/language/de/usage.txt
rm -f bin64/language/en/messages.txt
rm -f bin64/language/en/usage.txt
rm -f bin64/language/fr/messages.txt
rm -f bin64/language/fr/usage.txt
rm -f bin64/language/ja/messages.txt
rm -f bin64/language/ja/usage.txt
rm -f bin64/language/zh/messages.txt
rm -f bin64/language/zh/usage.txt
rm -f bin64/mlarb17
rm -f bin64/mlarb17.lic
rm -f bin64/mlarbiter.sh
rm -f bin64/mlarbstop
rm -f bin64/mlfiletransfer
rm -f bin64/mlgenreplayapi
rm -f bin64/mlprof
rm -f bin64/mlreplay
rm -f bin64/mlsrv17
rm -f bin64/mlsrv17.lic
rm -f bin64/mlstop
rm -f bin64/mltemplate
rm -f bin64/mluser
rm -f bin64/newdemo.sh
rm -f bin64/perlenv.pl
rm -f bin64/phpenv.php
rm -f bin64/rshost
rm -f bin64/rsoe2
rm -f bin64/run_migrator.sh
rm -f bin64/sa_config.csh
rm -f bin64/sa_config.sh
rm -f bin64/samonitor
rm -f bin64/samonitor.sh
rm -f bin64/samonitor.template
rm -f bin64/scjview
rm -f bin64/smstart.dat
rm -f bin64/smstop.dat
rm -f bin64/sqlpp
rm -f bin64/uldeploy
rm -f bin64/uleng17
rm -f bin64/ulerase
rm -f bin64/ulinfo
rm -f bin64/ulinit
rm -f bin64/ulload
rm -f bin64/ulstop
rm -f bin64/ulsync
rm -f bin64/ulunload
rm -f bin64/ulvalid
rm -f bin64/usm.xsd
rm -f bin64/viewcert
rm -f bin64s/createcert
rm -f bin64s/createkey
rm -f bin64s/dbbackup
rm -f bin64s/dbdsn
rm -f bin64s/dbeng17
rm -f bin64s/dberase
rm -f bin64s/dbexternc17
rm -f bin64s/dbfhide
rm -f bin64s/dbinfo
rm -f bin64s/dbinit
rm -f bin64s/dbisql
rm -f bin64s/dbisqlc
rm -f bin64s/dblic
rm -f bin64s/dblocate
rm -f bin64s/dblog
rm -f bin64s/dbmanageetd
rm -f bin64s/dbmlsync
rm -f bin64s/dbns17
rm -f bin64s/dbping
rm -f bin64s/dbprof
rm -f bin64s/dbremote
rm -f bin64s/dbspawn
rm -f bin64s/dbsrv17
rm -f bin64s/dbstats
rm -f bin64s/dbstop
rm -f bin64s/dbsupport
rm -f bin64s/dbsvc
rm -f bin64s/dbsvc_scripts/dbsvc_iface
rm -f bin64s/dbsvc_scripts/dbsvc_iface_lsb
rm -f bin64s/dbsvc_scripts/dbsvc_iface_rh
rm -f bin64s/dbsvc_scripts/dbsvc_iface_suse
rm -f bin64s/dbsvc_scripts/dbsvc_iface_systemd
rm -f bin64s/dbsvc_scripts/distro.sh
rm -f bin64s/dbsvc_scripts/svc_functions
rm -f bin64s/dbsvc_scripts/svc_t_dbeng
rm -f bin64s/dbsvc_scripts/svc_t_dbmlsync
rm -f bin64s/dbsvc_scripts/svc_t_dbns
rm -f bin64s/dbsvc_scripts/svc_t_dbremote
rm -f bin64s/dbsvc_scripts/svc_t_dbsrv
rm -f bin64s/dbsvc_scripts/svc_t_mlsrv
rm -f bin64s/dbsvc_scripts/svc_t_mlsync
rm -f bin64s/dbsvc_scripts/svc_t_mobilink
rm -f bin64s/dbsvc_scripts/svc_t_network
rm -f bin64s/dbsvc_scripts/svc_t_personal
rm -f bin64s/dbsvc_scripts/svc_t_rshost
rm -f bin64s/dbsvc_scripts/svc_t_rsoe
rm -f bin64s/dbsvc_scripts/svc_t_standalone
rm -f bin64s/dbsvc_scripts/utility.sh
rm -f bin64s/dbtran
rm -f bin64s/dbtsinfo
rm -f bin64s/dbunload
rm -f bin64s/dbunlspt
rm -f bin64s/dbupgrad
rm -f bin64s/dbvalid
rm -f bin64s/dbversion
rm -f bin64s/dbxtract
rm -f bin64s/htmlview
rm -f bin64s/jre180/.hotspot_compiler
rm -f bin64s/jre180/COPYRIGHT
rm -f bin64s/jre180/THIRDPARTYLICENSEREADME.txt
rm -f bin64s/jre180/Welcome.html
rm -f bin64s/jre180/bin/forkhelper
rm -f bin64s/jre180/bin/java
rm -f bin64s/jre180/bin/jjs
rm -f bin64s/jre180/bin/jvmmon
rm -f bin64s/jre180/bin/jvmmond
rm -f bin64s/jre180/bin/jvmprof
rm -f bin64s/jre180/bin/keytool
rm -f bin64s/jre180/bin/orbd
rm -f bin64s/jre180/bin/pack200
rm -f bin64s/jre180/bin/policytool
rm -f bin64s/jre180/bin/rmid
rm -f bin64s/jre180/bin/rmiregistry
rm -f bin64s/jre180/bin/servertool
rm -f bin64s/jre180/bin/tnameserv
rm -f bin64s/jre180/bin/unpack200
rm -f bin64s/jre180/buildinfo.txt
rm -f bin64s/jre180/lib/add_sapjvm_alternatives.sh
rm -f bin64s/jre180/lib/amd64/jli/libjli.so
rm -f bin64s/jre180/lib/amd64/jvm.cfg
rm -f bin64s/jre180/lib/amd64/libattach.so
rm -f bin64s/jre180/lib/amd64/libawt.so
rm -f bin64s/jre180/lib/amd64/libawt_headless.so
rm -f bin64s/jre180/lib/amd64/libawt_xawt.so
rm -f bin64s/jre180/lib/amd64/libdcpr.so
rm -f bin64s/jre180/lib/amd64/libdt_socket.so
rm -f bin64s/jre180/lib/amd64/libfontmanager.so
rm -f bin64s/jre180/lib/amd64/libhprof.so
rm -f bin64s/jre180/lib/amd64/libinstrument.so
rm -f bin64s/jre180/lib/amd64/libj2gss.so
rm -f bin64s/jre180/lib/amd64/libj2pcsc.so
rm -f bin64s/jre180/lib/amd64/libj2pkcs11.so
rm -f bin64s/jre180/lib/amd64/libjaas_unix.so
rm -f bin64s/jre180/lib/amd64/libjava.so
rm -f bin64s/jre180/lib/amd64/libjava_crw_demo.so
rm -f bin64s/jre180/lib/amd64/libjawt.so
rm -f bin64s/jre180/lib/amd64/libjdwp.so
rm -f bin64s/jre180/lib/amd64/libjpeg.so
rm -f bin64s/jre180/lib/amd64/libjsdt.so
rm -f bin64s/jre180/lib/amd64/libjsig.so
rm -f bin64s/jre180/lib/amd64/libjsound.so
rm -f bin64s/jre180/lib/amd64/libkcms.so
rm -f bin64s/jre180/lib/amd64/liblcms.so
rm -f bin64s/jre180/lib/amd64/libmanagement.so
rm -f bin64s/jre180/lib/amd64/libmlib_image.so
rm -f bin64s/jre180/lib/amd64/libnet.so
rm -f bin64s/jre180/lib/amd64/libnio.so
rm -f bin64s/jre180/lib/amd64/libnpt.so
rm -f bin64s/jre180/lib/amd64/libsapext.so
rm -f bin64s/jre180/lib/amd64/libsapjvm_inspector.so
rm -f bin64s/jre180/lib/amd64/libsapmanagement.so
rm -f bin64s/jre180/lib/amd64/libsaproc.so
rm -f bin64s/jre180/lib/amd64/libsapsession.so
rm -f bin64s/jre180/lib/amd64/libsctp.so
rm -f bin64s/jre180/lib/amd64/libsplashscreen.so
rm -f bin64s/jre180/lib/amd64/libsunec.so
rm -f bin64s/jre180/lib/amd64/libt2k.so
rm -f bin64s/jre180/lib/amd64/libunpack.so
rm -f bin64s/jre180/lib/amd64/libverify.so
rm -f bin64s/jre180/lib/amd64/libzip.so
rm -f bin64s/jre180/lib/amd64/server/Xusage.txt
rm -f bin64s/jre180/lib/amd64/server/libjsig.so
rm -f bin64s/jre180/lib/amd64/server/libjvm.so
rm -f bin64s/jre180/lib/amd64/server/sapjvm.info
rm -f bin64s/jre180/lib/calendars.properties
rm -f bin64s/jre180/lib/charsets.jar
rm -f bin64s/jre180/lib/classlist
rm -f bin64s/jre180/lib/cmm/CIEXYZ.pf
rm -f bin64s/jre180/lib/cmm/GRAY.pf
rm -f bin64s/jre180/lib/cmm/LINEAR_RGB.pf
rm -f bin64s/jre180/lib/cmm/PYCC.pf
rm -f bin64s/jre180/lib/cmm/sRGB.pf
rm -f bin64s/jre180/lib/content-types.properties
rm -f bin64s/jre180/lib/currency.data
rm -f bin64s/jre180/lib/ext/cldrdata.jar
rm -f bin64s/jre180/lib/ext/dnsns.jar
rm -f bin64s/jre180/lib/ext/jaccess.jar
rm -f bin64s/jre180/lib/ext/localedata.jar
rm -f bin64s/jre180/lib/ext/meta-index
rm -f bin64s/jre180/lib/ext/nashorn.jar
rm -f bin64s/jre180/lib/ext/sunec.jar
rm -f bin64s/jre180/lib/ext/sunjce_provider.jar
rm -f bin64s/jre180/lib/ext/sunpkcs11.jar
rm -f bin64s/jre180/lib/ext/zipfs.jar
rm -f bin64s/jre180/lib/flavormap.properties
rm -f bin64s/jre180/lib/fontconfig.RedHat.5.bfc
rm -f bin64s/jre180/lib/fontconfig.RedHat.5.properties.src
rm -f bin64s/jre180/lib/fontconfig.RedHat.6.bfc
rm -f bin64s/jre180/lib/fontconfig.RedHat.6.properties.src
rm -f bin64s/jre180/lib/fontconfig.SuSE.10.bfc
rm -f bin64s/jre180/lib/fontconfig.SuSE.10.properties.src
rm -f bin64s/jre180/lib/fontconfig.SuSE.11.bfc
rm -f bin64s/jre180/lib/fontconfig.SuSE.11.properties.src
rm -f bin64s/jre180/lib/fontconfig.Turbo.bfc
rm -f bin64s/jre180/lib/fontconfig.Turbo.properties.src
rm -f bin64s/jre180/lib/fontconfig.bfc
rm -f bin64s/jre180/lib/fontconfig.properties.src
rm -f bin64s/jre180/lib/fonts/LucidaBrightDemiBold.ttf
rm -f bin64s/jre180/lib/fonts/LucidaBrightDemiItalic.ttf
rm -f bin64s/jre180/lib/fonts/LucidaBrightItalic.ttf
rm -f bin64s/jre180/lib/fonts/LucidaBrightRegular.ttf
rm -f bin64s/jre180/lib/fonts/LucidaSansDemiBold.ttf
rm -f bin64s/jre180/lib/fonts/LucidaSansRegular.ttf
rm -f bin64s/jre180/lib/fonts/LucidaTypewriterBold.ttf
rm -f bin64s/jre180/lib/fonts/LucidaTypewriterRegular.ttf
rm -f bin64s/jre180/lib/fonts/fonts.dir
rm -f bin64s/jre180/lib/hijrah-config-umalqura.properties
rm -f bin64s/jre180/lib/images/cursors/cursors.properties
rm -f bin64s/jre180/lib/images/cursors/invalid32x32.gif
rm -f bin64s/jre180/lib/images/cursors/motif_CopyDrop32x32.gif
rm -f bin64s/jre180/lib/images/cursors/motif_CopyNoDrop32x32.gif
rm -f bin64s/jre180/lib/images/cursors/motif_LinkDrop32x32.gif
rm -f bin64s/jre180/lib/images/cursors/motif_LinkNoDrop32x32.gif
rm -f bin64s/jre180/lib/images/cursors/motif_MoveDrop32x32.gif
rm -f bin64s/jre180/lib/images/cursors/motif_MoveNoDrop32x32.gif
rm -f bin64s/jre180/lib/jce.jar
rm -f bin64s/jre180/lib/jexec
rm -f bin64s/jre180/lib/jsse.jar
rm -f bin64s/jre180/lib/jvm.hprof.txt
rm -f bin64s/jre180/lib/logging.properties
rm -f bin64s/jre180/lib/management-agent.jar
rm -f bin64s/jre180/lib/management/jmxremote.access
rm -f bin64s/jre180/lib/management/jmxremote.password.template
rm -f bin64s/jre180/lib/management/management.properties
rm -f bin64s/jre180/lib/management/snmp.acl.template
rm -f bin64s/jre180/lib/meta-index
rm -f bin64s/jre180/lib/net.properties
rm -f bin64s/jre180/lib/oblique-fonts/LucidaSansDemiOblique.ttf
rm -f bin64s/jre180/lib/oblique-fonts/LucidaSansOblique.ttf
rm -f bin64s/jre180/lib/oblique-fonts/LucidaTypewriterBoldOblique.ttf
rm -f bin64s/jre180/lib/oblique-fonts/LucidaTypewriterOblique.ttf
rm -f bin64s/jre180/lib/oblique-fonts/fonts.dir
rm -f bin64s/jre180/lib/psfont.properties.ja
rm -f bin64s/jre180/lib/psfontj2d.properties
rm -f bin64s/jre180/lib/remove_sapjvm_alternatives.sh
rm -f bin64s/jre180/lib/resources.jar
rm -f bin64s/jre180/lib/rt.jar
rm -f bin64s/jre180/lib/sapjvm-tools.jar
rm -f bin64s/jre180/lib/security/blacklist
rm -f bin64s/jre180/lib/security/blacklisted.certs
rm -f bin64s/jre180/lib/security/cacerts
rm -f bin64s/jre180/lib/security/java.policy
rm -f bin64s/jre180/lib/security/java.security
rm -f bin64s/jre180/lib/security/policy/limited/US_export_policy.jar
rm -f bin64s/jre180/lib/security/policy/limited/local_policy.jar
rm -f bin64s/jre180/lib/security/policy/unlimited/US_export_policy.jar
rm -f bin64s/jre180/lib/security/policy/unlimited/local_policy.jar
rm -f bin64s/jre180/lib/security/trusted.libraries
rm -f bin64s/jre180/lib/sound.properties
rm -f bin64s/jre180/lib/src_ecc.zip
rm -f bin64s/jre180/lib/tzdb.dat
rm -f bin64s/jsenv.js
rm -f bin64s/language/de/messages.txt
rm -f bin64s/language/de/usage.txt
rm -f bin64s/language/en/messages.txt
rm -f bin64s/language/en/usage.txt
rm -f bin64s/language/fr/messages.txt
rm -f bin64s/language/fr/usage.txt
rm -f bin64s/language/ja/messages.txt
rm -f bin64s/language/ja/usage.txt
rm -f bin64s/language/zh/messages.txt
rm -f bin64s/language/zh/usage.txt
rm -f bin64s/mlarb17
rm -f bin64s/mlarb17.lic
rm -f bin64s/mlarbiter.sh
rm -f bin64s/mlarbstop
rm -f bin64s/mlfiletransfer
rm -f bin64s/mlgenreplayapi
rm -f bin64s/mlprof
rm -f bin64s/mlreplay
rm -f bin64s/mlsrv17
rm -f bin64s/mlstop
rm -f bin64s/mltemplate
rm -f bin64s/mluser
rm -f bin64s/newdemo.sh
rm -f bin64s/perlenv.pl
rm -f bin64s/phpenv.php
rm -f bin64s/rshost
rm -f bin64s/rsoe2
rm -f bin64s/run_migrator.sh
rm -f bin64s/samonitor
rm -f bin64s/samonitor.sh
rm -f bin64s/samonitor.template
rm -f bin64s/scjview
rm -f bin64s/smstop.dat
rm -f bin64s/sqlpp
rm -f bin64s/uldeploy
rm -f bin64s/uleng17
rm -f bin64s/ulerase
rm -f bin64s/ulinfo
rm -f bin64s/ulinit
rm -f bin64s/ulload
rm -f bin64s/ulstop
rm -f bin64s/ulsync
rm -f bin64s/ulunload
rm -f bin64s/ulvalid
rm -f bin64s/usm.xsd
rm -f bin64s/viewcert
rm -f charsets/unicode/big5hk.uct
rm -f charsets/unicode/cp037.uct
rm -f charsets/unicode/cp1006.uct
rm -f charsets/unicode/cp1026.uct
rm -f charsets/unicode/cp1140.uct
rm -f charsets/unicode/cp1141.uct
rm -f charsets/unicode/cp1142.uct
rm -f charsets/unicode/cp1143.uct
rm -f charsets/unicode/cp1144.uct
rm -f charsets/unicode/cp1145.uct
rm -f charsets/unicode/cp1146.uct
rm -f charsets/unicode/cp1147.uct
rm -f charsets/unicode/cp1148.uct
rm -f charsets/unicode/cp1149.uct
rm -f charsets/unicode/cp1250.uct
rm -f charsets/unicode/cp1251.uct
rm -f charsets/unicode/cp1252.uct
rm -f charsets/unicode/cp1253.uct
rm -f charsets/unicode/cp1254.uct
rm -f charsets/unicode/cp1255.uct
rm -f charsets/unicode/cp1256.uct
rm -f charsets/unicode/cp1257.uct
rm -f charsets/unicode/cp1258.uct
rm -f charsets/unicode/cp273.uct
rm -f charsets/unicode/cp277.uct
rm -f charsets/unicode/cp278.uct
rm -f charsets/unicode/cp280.uct
rm -f charsets/unicode/cp284.uct
rm -f charsets/unicode/cp285.uct
rm -f charsets/unicode/cp297.uct
rm -f charsets/unicode/cp300.uct
rm -f charsets/unicode/cp424.uct
rm -f charsets/unicode/cp437.uct
rm -f charsets/unicode/cp500.uct
rm -f charsets/unicode/cp737.uct
rm -f charsets/unicode/cp775.uct
rm -f charsets/unicode/cp834.uct
rm -f charsets/unicode/cp835.uct
rm -f charsets/unicode/cp837.uct
rm -f charsets/unicode/cp850.uct
rm -f charsets/unicode/cp852.uct
rm -f charsets/unicode/cp855.uct
rm -f charsets/unicode/cp856.uct
rm -f charsets/unicode/cp857.uct
rm -f charsets/unicode/cp858.uct
rm -f charsets/unicode/cp860.uct
rm -f charsets/unicode/cp861.uct
rm -f charsets/unicode/cp862.uct
rm -f charsets/unicode/cp863.uct
rm -f charsets/unicode/cp864.uct
rm -f charsets/unicode/cp865.uct
rm -f charsets/unicode/cp866.uct
rm -f charsets/unicode/cp869.uct
rm -f charsets/unicode/cp871.uct
rm -f charsets/unicode/cp874.uct
rm -f charsets/unicode/cp874ibm.uct
rm -f charsets/unicode/cp932.uct
rm -f charsets/unicode/cp932ms.uct
rm -f charsets/unicode/cp932ms2.uct
rm -f charsets/unicode/cp932ms3.uct
rm -f charsets/unicode/cp936.uct
rm -f charsets/unicode/cp949.uct
rm -f charsets/unicode/cp950.uct
rm -f charsets/unicode/euccns.uct
rm -f charsets/unicode/eucgb.uct
rm -f charsets/unicode/eucksc.uct
rm -f charsets/unicode/gb18030.uct
rm -f charsets/unicode/greek8.uct
rm -f charsets/unicode/iso10.uct
rm -f charsets/unicode/iso13.uct
rm -f charsets/unicode/iso14.uct
rm -f charsets/unicode/iso15.uct
rm -f charsets/unicode/iso88592.uct
rm -f charsets/unicode/iso88593.uct
rm -f charsets/unicode/iso88594.uct
rm -f charsets/unicode/iso88595.uct
rm -f charsets/unicode/iso88596.uct
rm -f charsets/unicode/iso88597.uct
rm -f charsets/unicode/iso88598.uct
rm -f charsets/unicode/iso88599.uct
rm -f charsets/unicode/koi8.uct
rm -f charsets/unicode/mac.uct
rm -f charsets/unicode/mac_cyr.uct
rm -f charsets/unicode/mac_ee.uct
rm -f charsets/unicode/mac_euro.uct
rm -f charsets/unicode/mac_grk.uct
rm -f charsets/unicode/macgrk2.uct
rm -f charsets/unicode/macthai.uct
rm -f charsets/unicode/macturk.uct
rm -f charsets/unicode/roman8.uct
rm -f charsets/unicode/roman9.uct
rm -f charsets/unicode/sjis.uct
rm -f charsets/unicode/tis620.uct
rm -f charsets/unicode/turkish8.uct
rm -f collate/unicode/big5bin.ust
rm -f collate/unicode/cp932bin.ust
rm -f collate/unicode/cyrdict.ust
rm -f collate/unicode/dynix.ust
rm -f collate/unicode/eucjisbn.ust
rm -f collate/unicode/euckscbn.ust
rm -f collate/unicode/gb2312bn.ust
rm -f collate/unicode/gbpinyin.ust
rm -f collate/unicode/rusdict.ust
rm -f collate/unicode/sjisbin.ust
rm -f collate/unicode/turdict.ust
rm -f demo.db
rm -f demo.log
rm -f deployment/bin32/csconvert
rm -f deployment/bin32/dbinstall
rm -f deployment/bin32/gsetup
rm -f deployment/bin32/is_utf8
rm -f deployment/bin32s/csconvert
rm -f deployment/bin32s/dbinstall
rm -f deployment/bin32s/gsetup
rm -f deployment/bin32s/is_utf8
rm -f deployment/bin64/csconvert
rm -f deployment/bin64/dbinstall
rm -f deployment/bin64/gsetup
rm -f deployment/bin64/is_utf8
rm -f deployment/bin64s/csconvert
rm -f deployment/bin64s/dbinstall
rm -f deployment/bin64s/gsetup
rm -f deployment/bin64s/is_utf8
rm -f deployment/deploy.noarch.tic
rm -f deployment/deployment_wizard.sh
rm -f deployment/lib32/libdbicu17.so
rm -f deployment/lib32/libdbicu17.so.1
rm -f deployment/lib32/libdbicu17_r.so
rm -f deployment/lib32/libdbicu17_r.so.1
rm -f deployment/lib32/libdbtasks17.so
rm -f deployment/lib32/libdbtasks17.so.1
rm -f deployment/lib32/libdbtasks17_r.so
rm -f deployment/lib32/libdbtasks17_r.so.1
rm -f deployment/lib64/libdbicu17.so
rm -f deployment/lib64/libdbicu17.so.1
rm -f deployment/lib64/libdbicu17_r.so
rm -f deployment/lib64/libdbicu17_r.so.1
rm -f deployment/lib64/libdbtasks17.so
rm -f deployment/lib64/libdbtasks17.so.1
rm -f deployment/lib64/libdbtasks17_r.so
rm -f deployment/lib64/libdbtasks17_r.so.1
rm -f deployment/res/dbicudt17.dat
rm -f deployment/res/language/all_langs_icon_resources_utf8.txt
rm -f deployment/res/language/common.sh
rm -f deployment/res/language/de/messages.txt
rm -f deployment/res/language/en/messages.txt
rm -f deployment/res/language/fr/messages.txt
rm -f deployment/res/language/ja/messages.txt
rm -f deployment/res/language/zh/messages.txt
rm -f deployment/res/scripts/array.sh
rm -f deployment/res/scripts/checkupdates.sh
rm -f deployment/res/scripts/cleanup.sh
rm -f deployment/res/scripts/client_flow.sh
rm -f deployment/res/scripts/cmdline.sh
rm -f deployment/res/scripts/component_spt.sh
rm -f deployment/res/scripts/config.sh
rm -f deployment/res/scripts/console_ui.sh
rm -f deployment/res/scripts/csconvert.sh
rm -f deployment/res/scripts/csh_support.sh
rm -f deployment/res/scripts/dbcloud.sh
rm -f deployment/res/scripts/dbcloud_flow.sh
rm -f deployment/res/scripts/deploy_flow.sh
rm -f deployment/res/scripts/deploy_wizard.sh
rm -f deployment/res/scripts/directory.sh
rm -f deployment/res/scripts/diskspace.sh
rm -f deployment/res/scripts/distro.sh
rm -f deployment/res/scripts/doc_flow.sh
rm -f deployment/res/scripts/feature_tracking.sh
rm -f deployment/res/scripts/generated.sh
rm -f deployment/res/scripts/installicon.sh
rm -f deployment/res/scripts/interactive_ui.sh
rm -f deployment/res/scripts/language.sh
rm -f deployment/res/scripts/license.sh
rm -f deployment/res/scripts/licenser_flow.sh
rm -f deployment/res/scripts/links.sh
rm -f deployment/res/scripts/options.sh
rm -f deployment/res/scripts/os.sh
rm -f deployment/res/scripts/package.sh
rm -f deployment/res/scripts/panel.sh
rm -f deployment/res/scripts/platform.sh
rm -f deployment/res/scripts/populate_menus.sh
rm -f deployment/res/scripts/registration.sh
rm -f deployment/res/scripts/rollback.sh
rm -f deployment/res/scripts/runinstall.sh
rm -f deployment/res/scripts/samon.sh
rm -f deployment/res/scripts/samon_flow.sh
rm -f deployment/res/scripts/sh_support.sh
rm -f deployment/res/scripts/shortcuts.sh
rm -f deployment/res/scripts/sighndlr.sh
rm -f deployment/res/scripts/silent_ui.sh
rm -f deployment/res/scripts/sqlcentral.sh
rm -f deployment/res/scripts/standard_flow.sh
rm -f deployment/res/scripts/summary.sh
rm -f deployment/res/scripts/ui.sh
rm -f deployment/res/scripts/upgrade.sh
rm -f deployment/res/scripts/user.sh
rm -f deployment/res/scripts/utility.sh
rm -f deployment/res/scripts/versioning.sh
rm -f install_*.log
rm -f installed.ini
rm -f java/*.jpr
rm -f java/JComponents1700.jar
rm -f java/SCEditor1700.jar
rm -f java/apache_files.txt
rm -f java/apache_license_1.1.txt
rm -f java/apache_license_2.0.txt
rm -f java/batik-all-1.10.jar
rm -f java/commons-collections4-4.2.jar
rm -f java/commons-io-2.6.jar
rm -f java/commons-lang3-3.8.1.jar
rm -f java/commons-logging-1.2.jar
rm -f java/dbdiff.jar
rm -f java/dbodata.jar
rm -f java/debugger.jar
rm -f java/diffutils-1.2.1.jar
rm -f java/isql.jar
rm -f java/jetty-all-server-9.4.24.jar
rm -f java/jodbc4.jar
rm -f java/jsyblib1700.jar
rm -f java/migrator.jar
rm -f java/ml-templates.zip
rm -f java/mldesign.jar
rm -f java/mlnotif.jar
rm -f java/mlplugin.jar
rm -f java/mlprof.jar
rm -f java/mlscript.jar
rm -f java/mlstream.jar
rm -f java/mlsupport.jar
rm -f java/ngdbc.jar
rm -f java/rstool.jar
rm -f java/sa_java.sh
rm -f java/saip17.jar
rm -f java/sajdbc4.jar
rm -f java/sajvm.jar
rm -f java/salib.jar
rm -f java/samonlauncher.jar
rm -f java/saplugin.jar
rm -f java/servlet-api-3.1.0.jar
rm -f java/slf4j-1.7.25.jar
rm -f java/sqlcentral1700.jar
rm -f java/ulplugin.jar
rm -f java/velocity-engine-core-2.0-dep.jar
rm -f java/xml-apis-ext.jar
rm -f java/xmlgraphics-commons-2.3.jar
rm -f lib32/libdbcapi.so
rm -f lib32/libdbcapi.so.1
rm -f lib32/libdbcapi_r.so
rm -f lib32/libdbcapi_r.so.1
rm -f lib32/libdbcis17.so
rm -f lib32/libdbcis17.so.1
rm -f lib32/libdbcrypto.so
rm -f lib32/libdbcrypto.so.1.0.0
rm -f lib32/libdbencod17_r.so
rm -f lib32/libdbencod17_r.so.1
rm -f lib32/libdbextenv17_r.so
rm -f lib32/libdbextenv17_r.so.1
rm -f lib32/libdbextf.so
rm -f lib32/libdbextf.so.1
rm -f lib32/libdbfile17_r.so
rm -f lib32/libdbfile17_r.so.1
rm -f lib32/libdbfips17.so
rm -f lib32/libdbfips17.so.1
rm -f lib32/libdbfips17_r.so
rm -f lib32/libdbfips17_r.so.1
rm -f lib32/libdbftp17_r.so
rm -f lib32/libdbftp17_r.so.1
rm -f lib32/libdbhttp17_r.so
rm -f lib32/libdbhttp17_r.so.1
rm -f lib32/libdbicu17.so
rm -f lib32/libdbicu17.so.1
rm -f lib32/libdbicu17_r.so
rm -f lib32/libdbicu17_r.so.1
rm -f lib32/libdbicudt17.so
rm -f lib32/libdbicudt17.so.1
rm -f lib32/libdbjdbc17.so
rm -f lib32/libdbjdbc17.so.1
rm -f lib32/libdbjodbc17.so
rm -f lib32/libdbjodbc17.so.1
rm -f lib32/libdblaiod17.so
rm -f lib32/libdblaiod17.so.1
rm -f lib32/libdbldap17.so
rm -f lib32/libdbldap17.so.1
rm -f lib32/libdbldap17_r.so
rm -f lib32/libdbldap17_r.so.1
rm -f lib32/libdbldapfips17_r.so
rm -f lib32/libdbldapfips17_r.so.1
rm -f lib32/libdblib17.so
rm -f lib32/libdblib17.so.1
rm -f lib32/libdblib17_r.so
rm -f lib32/libdblib17_r.so.1
rm -f lib32/libdbmlsynccli17_r.so
rm -f lib32/libdbmlsynccli17_r.so.1
rm -f lib32/libdbodbc17.so
rm -f lib32/libdbodbc17.so.1
rm -f lib32/libdbodbc17_n.so
rm -f lib32/libdbodbc17_n.so.1
rm -f lib32/libdbodbc17_r.so
rm -f lib32/libdbodbc17_r.so.1
rm -f lib32/libdbodbcansi17_r.so
rm -f lib32/libdbodbcansi17_r.so.1
rm -f lib32/libdbodbcinst17_r.so
rm -f lib32/libdbodbcinst17_r.so.1
rm -f lib32/libdbodm17.so
rm -f lib32/libdbodm17.so.1
rm -f lib32/libdboftsp_r.so
rm -f lib32/libdboftsp_r.so.1
rm -f lib32/libdbperfapi17_r.so
rm -f lib32/libdbperfapi17_r.so.1
rm -f lib32/libdbput17_r.so
rm -f lib32/libdbput17_r.so.1
rm -f lib32/libdbrsa17.so
rm -f lib32/libdbrsa17.so.1
rm -f lib32/libdbrsa17_r.so
rm -f lib32/libdbrsa17_r.so.1
rm -f lib32/libdbrsakp17_r.so
rm -f lib32/libdbrsakp17_r.so.1
rm -f lib32/libdbscript17_r.so
rm -f lib32/libdbscript17_r.so.1
rm -f lib32/libdbserv17_r.so
rm -f lib32/libdbserv17_r.so.1
rm -f lib32/libdbsmtp17_r.so
rm -f lib32/libdbsmtp17_r.so.1
rm -f lib32/libdbsrvmon17_r.so
rm -f lib32/libdbsrvmon17_r.so.1
rm -f lib32/libdbssl.so
rm -f lib32/libdbssl.so.1.0.0
rm -f lib32/libdbtasks17.so
rm -f lib32/libdbtasks17.so.1
rm -f lib32/libdbtasks17_r.so
rm -f lib32/libdbtasks17_r.so.1
rm -f lib32/libdbtool17_r.so
rm -f lib32/libdbtool17_r.so.1
rm -f lib32/libdbxgtk17_r.so
rm -f lib32/libdbxgtk17_r.so.1
rm -f lib32/libjsyblib1700_r.so
rm -f lib32/libjsyblib1700_r.so.1
rm -f lib32/libmlcrsa17_r.so
rm -f lib32/libmlcrsa17_r.so.1
rm -f lib32/libmlcrsafips17_r.so
rm -f lib32/libmlcrsafips17_r.so.1
rm -f lib32/libmlczlib17_r.so
rm -f lib32/libmlczlib17_r.so.1
rm -f lib32/libmljstrm17_r.so
rm -f lib32/libmljstrm17_r.so.1
rm -f lib32/libodbcinst.so
rm -f lib32/libodbcinst.so.1
rm -f lib32/libodbcinst.so.2
rm -f lib32/libsapcrypto.so
rm -f lib32/libsapcryptofips.so
rm -f lib32/libslcryptokernel.so
rm -f lib32/libslcryptokernel.so.sha256
rm -f lib32/libulodbc17_r.so
rm -f lib32/libulodbc17_r.so.1
rm -f lib32/libulutils17_r.so
rm -f lib32/libulutils17_r.so.1
rm -f lib64/libdbcapi.so
rm -f lib64/libdbcapi.so.1
rm -f lib64/libdbcapi_r.so
rm -f lib64/libdbcapi_r.so.1
rm -f lib64/libdbcis17.so
rm -f lib64/libdbcis17.so.1
rm -f lib64/libdbcrypto.so
rm -f lib64/libdbcrypto.so.1.0.0
rm -f lib64/libdbencod17_r.so
rm -f lib64/libdbencod17_r.so.1
rm -f lib64/libdbextenv17_r.so
rm -f lib64/libdbextenv17_r.so.1
rm -f lib64/libdbextf.so
rm -f lib64/libdbextf.so.1
rm -f lib64/libdbfile17_r.so
rm -f lib64/libdbfile17_r.so.1
rm -f lib64/libdbfips17.so
rm -f lib64/libdbfips17.so.1
rm -f lib64/libdbfips17_r.so
rm -f lib64/libdbfips17_r.so.1
rm -f lib64/libdbftp17_r.so
rm -f lib64/libdbftp17_r.so.1
rm -f lib64/libdbhttp17_r.so
rm -f lib64/libdbhttp17_r.so.1
rm -f lib64/libdbicu17.so
rm -f lib64/libdbicu17.so.1
rm -f lib64/libdbicu17_r.so
rm -f lib64/libdbicu17_r.so.1
rm -f lib64/libdbicudt17.so
rm -f lib64/libdbicudt17.so.1
rm -f lib64/libdbjdbc17.so
rm -f lib64/libdbjdbc17.so.1
rm -f lib64/libdbjodbc17.so
rm -f lib64/libdbjodbc17.so.1
rm -f lib64/libdblaiod17.so
rm -f lib64/libdblaiod17.so.1
rm -f lib64/libdbldap17.so
rm -f lib64/libdbldap17.so.1
rm -f lib64/libdbldap17_r.so
rm -f lib64/libdbldap17_r.so.1
rm -f lib64/libdbldapfips17_r.so
rm -f lib64/libdbldapfips17_r.so.1
rm -f lib64/libdblib17.so
rm -f lib64/libdblib17.so.1
rm -f lib64/libdblib17_r.so
rm -f lib64/libdblib17_r.so.1
rm -f lib64/libdbmlsynccli17_r.so
rm -f lib64/libdbmlsynccli17_r.so.1
rm -f lib64/libdbodbc17.so
rm -f lib64/libdbodbc17.so.1
rm -f lib64/libdbodbc17_n.so
rm -f lib64/libdbodbc17_n.so.1
rm -f lib64/libdbodbc17_r.so
rm -f lib64/libdbodbc17_r.so.1
rm -f lib64/libdbodbcansi17_r.so
rm -f lib64/libdbodbcansi17_r.so.1
rm -f lib64/libdbodbcinst17_r.so
rm -f lib64/libdbodbcinst17_r.so.1
rm -f lib64/libdbodm17.so
rm -f lib64/libdbodm17.so.1
rm -f lib64/libdboftsp_r.so
rm -f lib64/libdboftsp_r.so.1
rm -f lib64/libdboraodbc17_r.so
rm -f lib64/libdboraodbc17_r.so.1
rm -f lib64/libdbperfapi17_r.so
rm -f lib64/libdbperfapi17_r.so.1
rm -f lib64/libdbput17_r.so
rm -f lib64/libdbput17_r.so.1
rm -f lib64/libdbrsa17.so
rm -f lib64/libdbrsa17.so.1
rm -f lib64/libdbrsa17_r.so
rm -f lib64/libdbrsa17_r.so.1
rm -f lib64/libdbrsakp17_r.so
rm -f lib64/libdbrsakp17_r.so.1
rm -f lib64/libdbscript17_r.so
rm -f lib64/libdbscript17_r.so.1
rm -f lib64/libdbserv17_r.so
rm -f lib64/libdbserv17_r.so.1
rm -f lib64/libdbsmtp17_r.so
rm -f lib64/libdbsmtp17_r.so.1
rm -f lib64/libdbsrvmon17_r.so
rm -f lib64/libdbsrvmon17_r.so.1
rm -f lib64/libdbssl.so
rm -f lib64/libdbssl.so.1.0.0
rm -f lib64/libdbtasks17.so
rm -f lib64/libdbtasks17.so.1
rm -f lib64/libdbtasks17_r.so
rm -f lib64/libdbtasks17_r.so.1
rm -f lib64/libdbtool17_r.so
rm -f lib64/libdbtool17_r.so.1
rm -f lib64/libdbxgtk17_r.so
rm -f lib64/libdbxgtk17_r.so.1
rm -f lib64/libjsyblib1700_r.so
rm -f lib64/libjsyblib1700_r.so.1
rm -f lib64/libmlcrsa17_r.so
rm -f lib64/libmlcrsa17_r.so.1
rm -f lib64/libmlcrsafips17_r.so
rm -f lib64/libmlcrsafips17_r.so.1
rm -f lib64/libmlczlib17_r.so
rm -f lib64/libmlczlib17_r.so.1
rm -f lib64/libmljava17_r.so
rm -f lib64/libmljava17_r.so.1
rm -f lib64/libmljodbc17.so
rm -f lib64/libmljodbc17.so.1
rm -f lib64/libmljstrm17_r.so
rm -f lib64/libmljstrm17_r.so.1
rm -f lib64/libmlodbc17_r.so
rm -f lib64/libmlodbc17_r.so.1
rm -f lib64/libmlserv17_r.so
rm -f lib64/libmlserv17_r.so.1
rm -f lib64/libmlsmtp17.so
rm -f lib64/libmlsmtp17.so.1
rm -f lib64/libmlsql17_r.so
rm -f lib64/libmlsql17_r.so.1
rm -f lib64/libodbcinst.so
rm -f lib64/libodbcinst.so.1
rm -f lib64/libodbcinst.so.2
rm -f lib64/libsapcrypto.so
rm -f lib64/libsapcryptofips.so
rm -f lib64/libslcryptokernel.so
rm -f lib64/libslcryptokernel.so.sha256
rm -f lib64/libulodbc17_r.so
rm -f lib64/libulodbc17_r.so.1
rm -f lib64/libulscutil17.so
rm -f lib64/libulscutil17.so.1
rm -f lib64/libulutils17_r.so
rm -f lib64/libulutils17_r.so.1
rm -f lib64/ncs.so
rm -f lib64/sapcpp47.so
rm -f mobilink/mlarbiter.control
rm -f mobilink/mltemplate/README.txt
rm -f mobilink/mltemplate/helpers/sqlhelpers.js
rm -f mobilink/mltemplate/javascript/generate.js
rm -f mobilink/mltemplate/javascript/handlebars.js
rm -f mobilink/mltemplate/javascript/prepare.js
rm -f mobilink/mltemplate/javascript/schema.js
rm -f mobilink/mltemplate/javascript/syncmodel.js
rm -f mobilink/mltemplate/javascript/system.js
rm -f mobilink/mltemplate/templates/consdb/hana/snapshot_download_scripts.hbs
rm -f mobilink/mltemplate/templates/consdb/hana/timestamp_download_schema.hbs
rm -f mobilink/mltemplate/templates/consdb/hana/timestamp_download_scripts.hbs
rm -f mobilink/mltemplate/templates/consdb/hana/upload_consdb_wins_col_scripts.hbs
rm -f mobilink/mltemplate/templates/consdb/hana/upload_consdb_wins_scripts.hbs
rm -f mobilink/mltemplate/templates/consdb/hana/upload_remdb_wins_col_scripts.hbs
rm -f mobilink/mltemplate/templates/consdb/hana/upload_scripts.hbs
rm -f mobilink/mltemplate/templates/consdb/sqla/snapshot_download_scripts.hbs
rm -f mobilink/mltemplate/templates/consdb/sqla/timestamp_download_schema.hbs
rm -f mobilink/mltemplate/templates/consdb/sqla/timestamp_download_scripts.hbs
rm -f mobilink/mltemplate/templates/consdb/sqla/upload_consdb_wins_col_scripts.hbs
rm -f mobilink/mltemplate/templates/consdb/sqla/upload_consdb_wins_scripts.hbs
rm -f mobilink/mltemplate/templates/consdb/sqla/upload_remdb_wins_col_scripts.hbs
rm -f mobilink/mltemplate/templates/consdb/sqla/upload_scripts.hbs
rm -f mobilink/setup/odbc.ini.sample
rm -f mobilink/setup/syncase.sql
rm -f mobilink/setup/syncdb2.sql
rm -f mobilink/setup/synchana.sql
rm -f mobilink/setup/synciq.sql
rm -f mobilink/setup/syncmys.sql
rm -f mobilink/setup/syncora.sql
rm -f mobilink/setup/syncsa.sql
rm -f mobilink/upgrade/10.0.x/upgrade_ase.sql
rm -f mobilink/upgrade/10.0.x/upgrade_db2.sql
rm -f mobilink/upgrade/10.0.x/upgrade_ora.sql
rm -f mobilink/upgrade/10.0.x/upgrade_sa.sql
rm -f mobilink/upgrade/11.0.x/upgrade_ase.sql
rm -f mobilink/upgrade/11.0.x/upgrade_db2.sql
rm -f mobilink/upgrade/11.0.x/upgrade_mys.sql
rm -f mobilink/upgrade/11.0.x/upgrade_ora.sql
rm -f mobilink/upgrade/11.0.x/upgrade_sa.sql
rm -f mobilink/upgrade/12.0.0/upgrade_ase.sql
rm -f mobilink/upgrade/12.0.0/upgrade_db2.sql
rm -f mobilink/upgrade/12.0.0/upgrade_mys.sql
rm -f mobilink/upgrade/12.0.0/upgrade_ora.sql
rm -f mobilink/upgrade/12.0.0/upgrade_sa.sql
rm -f mobilink/upgrade/12.0.1/upgrade_ase.sql
rm -f mobilink/upgrade/12.0.1/upgrade_db2.sql
rm -f mobilink/upgrade/12.0.1/upgrade_iq.sql
rm -f mobilink/upgrade/12.0.1/upgrade_mys.sql
rm -f mobilink/upgrade/12.0.1/upgrade_ora.sql
rm -f mobilink/upgrade/12.0.1/upgrade_sa.sql
rm -f mobilink/upgrade/16.0.0/upgrade_hana.sql
rm -f mobilink/upgrade/16.0.0/upgrade_sa.sql
rm -f mobilink/upgrade/17.0.0/upgrade_hana.sql
rm -f mobilink/upgrade/17.0.0/upgrade_sa.sql
rm -f mobilink/upgrade/7.0.x/readme.txt
rm -f mobilink/upgrade/7.0.x/upgrade_asa.sql
rm -f mobilink/upgrade/7.0.x/upgrade_ase.sql
rm -f mobilink/upgrade/7.0.x/upgrade_db2.sql
rm -f mobilink/upgrade/7.0.x/upgrade_db2tolong.sql
rm -f mobilink/upgrade/7.0.x/upgrade_ora.sql
rm -f mobilink/upgrade/8.0.0/readme.txt
rm -f mobilink/upgrade/8.0.0/upgrade_asa.sql
rm -f mobilink/upgrade/8.0.0/upgrade_ase.sql
rm -f mobilink/upgrade/8.0.0/upgrade_db2.sql
rm -f mobilink/upgrade/8.0.0/upgrade_db2tolong.sql
rm -f mobilink/upgrade/8.0.0/upgrade_ora.sql
rm -f mobilink/upgrade/8.0.1/readme.txt
rm -f mobilink/upgrade/8.0.1/upgrade_asa.sql
rm -f mobilink/upgrade/8.0.1/upgrade_ase.sql
rm -f mobilink/upgrade/8.0.1/upgrade_db2.sql
rm -f mobilink/upgrade/8.0.1/upgrade_db2tolong.sql
rm -f mobilink/upgrade/8.0.1/upgrade_ora.sql
rm -f mobilink/upgrade/8.0.x/readme.txt
rm -f mobilink/upgrade/8.0.x/upgrade_asa.sql
rm -f mobilink/upgrade/8.0.x/upgrade_ase.sql
rm -f mobilink/upgrade/8.0.x/upgrade_db2.sql
rm -f mobilink/upgrade/8.0.x/upgrade_db2tolong.sql
rm -f mobilink/upgrade/8.0.x/upgrade_ora.sql
rm -f mobilink/upgrade/9.0.0/readme.txt
rm -f mobilink/upgrade/9.0.0/upgrade_asa.sql
rm -f mobilink/upgrade/9.0.0/upgrade_ase.sql
rm -f mobilink/upgrade/9.0.0/upgrade_db2.sql
rm -f mobilink/upgrade/9.0.0/upgrade_db2tolong.sql
rm -f mobilink/upgrade/9.0.0/upgrade_ora.sql
rm -f mobilink/upgrade/9.0.1/readme.txt
rm -f mobilink/upgrade/9.0.1/upgrade_asa.sql
rm -f mobilink/upgrade/9.0.1/upgrade_ase.sql
rm -f mobilink/upgrade/9.0.1/upgrade_db2.sql
rm -f mobilink/upgrade/9.0.1/upgrade_ora.sql
rm -f mobilink/upgrade/9.0.2/upgrade_asa.sql
rm -f mobilink/upgrade/9.0.2/upgrade_ase.sql
rm -f mobilink/upgrade/9.0.2/upgrade_db2.sql
rm -f mobilink/upgrade/9.0.2/upgrade_ora.sql
rm -f node/sqlanywhere-xs/bin32/sqlanywhere_xs_v10.node
rm -f node/sqlanywhere-xs/bin32/sqlanywhere_xs_v5.node
rm -f node/sqlanywhere-xs/bin32/sqlanywhere_xs_v6.node
rm -f node/sqlanywhere-xs/bin32/sqlanywhere_xs_v7.node
rm -f node/sqlanywhere-xs/bin32/sqlanywhere_xs_v8.node
rm -f node/sqlanywhere-xs/bin32/sqlanywhere_xs_v9.node
rm -f node/sqlanywhere-xs/bin32s/sqlanywhere_xs_v10.node
rm -f node/sqlanywhere-xs/bin32s/sqlanywhere_xs_v5.node
rm -f node/sqlanywhere-xs/bin32s/sqlanywhere_xs_v6.node
rm -f node/sqlanywhere-xs/bin32s/sqlanywhere_xs_v7.node
rm -f node/sqlanywhere-xs/bin32s/sqlanywhere_xs_v8.node
rm -f node/sqlanywhere-xs/bin32s/sqlanywhere_xs_v9.node
rm -f node/sqlanywhere-xs/bin64/sqlanywhere_xs_v10.node
rm -f node/sqlanywhere-xs/bin64/sqlanywhere_xs_v5.node
rm -f node/sqlanywhere-xs/bin64/sqlanywhere_xs_v6.node
rm -f node/sqlanywhere-xs/bin64/sqlanywhere_xs_v7.node
rm -f node/sqlanywhere-xs/bin64/sqlanywhere_xs_v8.node
rm -f node/sqlanywhere-xs/bin64/sqlanywhere_xs_v9.node
rm -f node/sqlanywhere-xs/bin64s/sqlanywhere_xs_v10.node
rm -f node/sqlanywhere-xs/bin64s/sqlanywhere_xs_v5.node
rm -f node/sqlanywhere-xs/bin64s/sqlanywhere_xs_v6.node
rm -f node/sqlanywhere-xs/bin64s/sqlanywhere_xs_v7.node
rm -f node/sqlanywhere-xs/bin64s/sqlanywhere_xs_v8.node
rm -f node/sqlanywhere-xs/bin64s/sqlanywhere_xs_v9.node
rm -f node/sqlanywhere-xs/lib/index.js
rm -f node/sqlanywhere-xs/package.json
rm -f node/sqlanywhere_jsextenv/bin32/jsextenv_v10.node
rm -f node/sqlanywhere_jsextenv/bin32/jsextenv_v5.node
rm -f node/sqlanywhere_jsextenv/bin32/jsextenv_v6.node
rm -f node/sqlanywhere_jsextenv/bin32/jsextenv_v7.node
rm -f node/sqlanywhere_jsextenv/bin32/jsextenv_v8.node
rm -f node/sqlanywhere_jsextenv/bin32/jsextenv_v9.node
rm -f node/sqlanywhere_jsextenv/bin32s/jsextenv_v10.node
rm -f node/sqlanywhere_jsextenv/bin32s/jsextenv_v5.node
rm -f node/sqlanywhere_jsextenv/bin32s/jsextenv_v6.node
rm -f node/sqlanywhere_jsextenv/bin32s/jsextenv_v7.node
rm -f node/sqlanywhere_jsextenv/bin32s/jsextenv_v8.node
rm -f node/sqlanywhere_jsextenv/bin32s/jsextenv_v9.node
rm -f node/sqlanywhere_jsextenv/bin64/jsextenv_v10.node
rm -f node/sqlanywhere_jsextenv/bin64/jsextenv_v5.node
rm -f node/sqlanywhere_jsextenv/bin64/jsextenv_v6.node
rm -f node/sqlanywhere_jsextenv/bin64/jsextenv_v7.node
rm -f node/sqlanywhere_jsextenv/bin64/jsextenv_v8.node
rm -f node/sqlanywhere_jsextenv/bin64/jsextenv_v9.node
rm -f node/sqlanywhere_jsextenv/bin64s/jsextenv_v10.node
rm -f node/sqlanywhere_jsextenv/bin64s/jsextenv_v5.node
rm -f node/sqlanywhere_jsextenv/bin64s/jsextenv_v6.node
rm -f node/sqlanywhere_jsextenv/bin64s/jsextenv_v7.node
rm -f node/sqlanywhere_jsextenv/bin64s/jsextenv_v8.node
rm -f node/sqlanywhere_jsextenv/bin64s/jsextenv_v9.node
rm -f node/sqlanywhere_jsextenv/lib/index.js
rm -f node/sqlanywhere_jsextenv/package.json
rm -f rdme*.ebf
rm -f rdme_17010_core_ebf_6127.html
rm -f rdme_17010_core_ebf_6127.txt
rm -f rdme_17010_ebf_6127.html
rm -f rdme_17010_ebf_6127.txt
rm -f readme_de.txt
rm -f readme_en.txt
rm -f readme_fr.txt
rm -f readme_ja.txt
rm -f readme_zh.txt
rm -f relayserver/apache22/bin64/mod_rs_ap22_admin.so.1
rm -f relayserver/apache22/bin64/mod_rs_ap22_client.so.1
rm -f relayserver/apache22/bin64/mod_rs_ap22_server.so.1
rm -f relayserver/apache22/bin64/mod_rs_ap_admin.so
rm -f relayserver/apache22/bin64/mod_rs_ap_client.so
rm -f relayserver/apache22/bin64/mod_rs_ap_server.so
rm -f relayserver/apache22/bin64/rshost
rm -f relayserver/apache22/bin64s/mod_rs_ap22_admin.so.1
rm -f relayserver/apache22/bin64s/mod_rs_ap22_client.so.1
rm -f relayserver/apache22/bin64s/mod_rs_ap22_server.so.1
rm -f relayserver/apache22/bin64s/mod_rs_ap_admin.so
rm -f relayserver/apache22/bin64s/mod_rs_ap_client.so
rm -f relayserver/apache22/bin64s/mod_rs_ap_server.so
rm -f relayserver/apache22/bin64s/rshost
rm -f relayserver/apache24/bin64/mod_rs_ap24_admin.so.1
rm -f relayserver/apache24/bin64/mod_rs_ap24_client.so.1
rm -f relayserver/apache24/bin64/mod_rs_ap24_server.so.1
rm -f relayserver/apache24/bin64/mod_rs_ap_admin.so
rm -f relayserver/apache24/bin64/mod_rs_ap_client.so
rm -f relayserver/apache24/bin64/mod_rs_ap_server.so
rm -f relayserver/apache24/bin64/rshost
rm -f relayserver/apache24/bin64s/mod_rs_ap24_admin.so.1
rm -f relayserver/apache24/bin64s/mod_rs_ap24_client.so.1
rm -f relayserver/apache24/bin64s/mod_rs_ap24_server.so.1
rm -f relayserver/apache24/bin64s/mod_rs_ap_admin.so
rm -f relayserver/apache24/bin64s/mod_rs_ap_client.so
rm -f relayserver/apache24/bin64s/mod_rs_ap_server.so
rm -f relayserver/apache24/bin64s/rshost
rm -f relayserver/quicksetup_apache/__ap-setup__.sh
rm -f relayserver/quicksetup_apache/__funcs__.sh
rm -f relayserver/quicksetup_apache/add_envvars_path.pl
rm -f relayserver/quicksetup_apache/add_rs_config.pl
rm -f relayserver/quicksetup_apache/ap-setup.sh
rm -f relayserver/quicksetup_apache/remove_rs_config.pl
rm -f relayserver/quicksetup_apache/tee.pl
rm -f relayserver/rs.config.sample
rm -f res/DBProfiler.png
rm -f res/InteractiveSQL.png
rm -f res/MobiLinkMonitor.png
rm -f res/SAMonitor16.png
rm -f res/SQLAnywhere.png
rm -f res/SQLAnywhereServer.png
rm -f res/SQLCentral.png
rm -f res/dblgde17_iso_1.res
rm -f res/dblgde17_utf8.res
rm -f res/dblgen17.res
rm -f res/dblgfr17_iso_1.res
rm -f res/dblgfr17_utf8.res
rm -f res/dblgja17_eucjis.res
rm -f res/dblgja17_sjis.res
rm -f res/dblgja17_utf8.res
rm -f res/dblgzh17_cp936.res
rm -f res/dblgzh17_eucgb.res
rm -f res/dblgzh17_utf8.res
rm -f res/dbusde_iso_1.res
rm -f res/dbusde_utf8.res
rm -f res/dbusen.res
rm -f res/dbusja_eucjis.res
rm -f res/dbusja_sjis.res
rm -f res/dbusja_utf8.res
rm -f res/dbuszh_cp936.res
rm -f res/dbuszh_eucgb.res
rm -f res/dbuszh_utf8.res
rm -f res/sqlany.cvf
rm -f samonitor.db
rm -f samonitor.log
rm -f samples/certificates/readme.txt
rm -f samples/certificates/rsaclient.id
rm -f samples/certificates/rsaclient_nopwd.id
rm -f samples/certificates/rsaroot.crt
rm -f samples/certificates/rsaroot.key
rm -f samples/certificates/rsaserver.id
rm -f samples/certificates/rsaserver_nopwd.id
rm -f samples/mobilink/contact/build.sh
rm -f samples/mobilink/contact/build_consol.sql
rm -f samples/mobilink/contact/build_remote.sql
rm -f samples/mobilink/contact/clean.sh
rm -f samples/mobilink/contact/customize.sql
rm -f samples/mobilink/contact/mlmaint.sql
rm -f samples/mobilink/contact/readme.txt
rm -f samples/mobilink/contact/readme_ja.txt
rm -f samples/mobilink/contact/report.sh
rm -f samples/mobilink/contact/report.sql
rm -f samples/mobilink/contact/step1.sh
rm -f samples/mobilink/contact/step2.sh
rm -f samples/mobilink/contact/step3.sh
rm -f samples/mobilink/custdb/project.mlp
rm -f samples/mobilink/globalautoincrement/build.sh
rm -f samples/mobilink/globalautoincrement/build_consol.sql
rm -f samples/mobilink/globalautoincrement/build_remote.sql
rm -f samples/mobilink/globalautoincrement/clean.sh
rm -f samples/mobilink/globalautoincrement/consol_inserts.sql
rm -f samples/mobilink/globalautoincrement/readme.txt
rm -f samples/mobilink/globalautoincrement/readme_ja.txt
rm -f samples/mobilink/globalautoincrement/remote_1_inserts.sql
rm -f samples/mobilink/globalautoincrement/remote_2_inserts.sql
rm -f samples/mobilink/globalautoincrement/report.sh
rm -f samples/mobilink/globalautoincrement/report.sql
rm -f samples/mobilink/globalautoincrement/step1.sh
rm -f samples/mobilink/globalautoincrement/step2.sh
rm -f samples/mobilink/globalautoincrement/step3.sh
rm -f samples/mobilink/java_authentication/CustEmpScripts.java
rm -f samples/mobilink/java_authentication/add_data_consol.sql
rm -f samples/mobilink/java_authentication/build.sh
rm -f samples/mobilink/java_authentication/build_consol.sql
rm -f samples/mobilink/java_authentication/build_remote.sql
rm -f samples/mobilink/java_authentication/clean.sh
rm -f samples/mobilink/java_authentication/readme.txt
rm -f samples/mobilink/java_authentication/readme_ja.txt
rm -f samples/mobilink/java_authentication/report.sh
rm -f samples/mobilink/java_authentication/report_consol.sql
rm -f samples/mobilink/java_authentication/report_remote.sql
rm -f samples/mobilink/java_authentication/step1.sh
rm -f samples/mobilink/java_authentication/step2.sh
rm -f samples/mobilink/java_authentication/step3.sh
rm -f samples/mobilink/mlreplay/build.sh
rm -f samples/mobilink/mlreplay/clean.sh
rm -f samples/mobilink/mlreplay/cons.sql
rm -f samples/mobilink/mlreplay/readme.txt
rm -f samples/mobilink/mlreplay/readme_ja.txt
rm -f samples/mobilink/mlreplay/remote.sql
rm -f samples/mobilink/mlreplay/report.sh
rm -f samples/mobilink/mlreplay/step1.sh
rm -f samples/mobilink/mlreplay/step2.sh
rm -f samples/mobilink/mlreplay/step3.sh
rm -f samples/mobilink/mlreplay/step4.sh
rm -f samples/mobilink/mlreplay/step5.sh
rm -f samples/mobilink/mlreplay/step6.sh
rm -f samples/mobilink/mlreplay/step7.sh
rm -f samples/mobilink/mlreplay/step8.sh
rm -f samples/mobilink/mltemplate/build.xml
rm -f samples/mobilink/mltemplate/clean.sh
rm -f samples/mobilink/mltemplate/helper/custom_helpers.js
rm -f samples/mobilink/mltemplate/project.json
rm -f samples/mobilink/mltemplate/readme.txt
rm -f samples/mobilink/mltemplate/report.sh
rm -f samples/mobilink/mltemplate/step1.sh
rm -f samples/mobilink/mltemplate/step2.sh
rm -f samples/mobilink/mltemplate/step3.sh
rm -f samples/mobilink/mltemplate/step4.sh
rm -f samples/mobilink/mltemplate/template/mobilink/cdb/sqla/basic/load.hbs
rm -f samples/mobilink/mltemplate/template/mobilink/cdb/sqla/basic/shadow_table.hbs
rm -f samples/mobilink/mltemplate/template/mobilink/cdb/sqla/basic/stored_procedure.hbs
rm -f samples/mobilink/mltemplate/template/mobilink/cdb/sqla/basic/sync_script.hbs
rm -f samples/mobilink/mltemplate/template/mobilink/cdb/sqla/basic/trigger.hbs
rm -f samples/mobilink/mltemplate/template/mobilink/cdb/sqla/test/report.hbs
rm -f samples/mobilink/mltemplate/template/mobilink/rdb/sqla/publication.hbs
rm -f samples/mobilink/mltemplate/template/mobilink/rdb/sqla/schema.hbs
rm -f samples/mobilink/mltemplate/template/mobilink/rdb/sqla/subscription.hbs
rm -f samples/mobilink/mltemplate/template/mobilink/rdb/sqla/table.hbs
rm -f samples/mobilink/mltemplate/template/mobilink/rdb/sqla/test/report.hbs
rm -f samples/mobilink/partitioning/build.sh
rm -f samples/mobilink/partitioning/build_consol.sql
rm -f samples/mobilink/partitioning/build_remote.sql
rm -f samples/mobilink/partitioning/clean.sh
rm -f samples/mobilink/partitioning/consol_inserts.sql
rm -f samples/mobilink/partitioning/readme.txt
rm -f samples/mobilink/partitioning/readme_ja.txt
rm -f samples/mobilink/partitioning/remote_1_inserts.sql
rm -f samples/mobilink/partitioning/remote_2_inserts.sql
rm -f samples/mobilink/partitioning/report.sh
rm -f samples/mobilink/partitioning/report.sql
rm -f samples/mobilink/partitioning/step1.sh
rm -f samples/mobilink/partitioning/step2.sh
rm -f samples/mobilink/partitioning/step3.sh
rm -f samples/sample_config32.sh
rm -f samples/sample_config64.sh
rm -f samples/sample_env32.csh
rm -f samples/sample_env32.sh
rm -f samples/sample_env64.csh
rm -f samples/sample_env64.sh
rm -f samples/sqlanywhere/c/build.sh
rm -f samples/sqlanywhere/c/clean.sh
rm -f samples/sqlanywhere/c/cur.sqc
rm -f samples/sqlanywhere/c/dcur.sqc
rm -f samples/sqlanywhere/c/example.h
rm -f samples/sqlanywhere/c/mainch.c
rm -f samples/sqlanywhere/c/odbc.c
rm -f samples/sqlanywhere/c/readme.txt
rm -f samples/sqlanywhere/dbtools/build.sh
rm -f samples/sqlanywhere/dbtools/clean.sh
rm -f samples/sqlanywhere/dbtools/main.cpp
rm -f samples/sqlanywhere/dbtools/readme.txt
rm -f samples/sqlanywhere/dbtools/readme_ja.txt
rm -f samples/sqlanywhere/dbtools/run.sh
rm -f samples/sqlanywhere/diskfull/build.sh
rm -f samples/sqlanywhere/diskfull/clean.sh
rm -f samples/sqlanywhere/diskfull/diskfull.cpp
rm -f samples/sqlanywhere/diskfull/readme.txt
rm -f samples/sqlanywhere/diskfull/readme_ja.txt
rm -f samples/sqlanywhere/diskfull/show_exports.sh
rm -f samples/sqlanywhere/externalenvironments/externc/datatype.sql
rm -f samples/sqlanywhere/externalenvironments/externc/resultset.cpp
rm -f samples/sqlanywhere/externalenvironments/externc/resultset.sql
rm -f samples/sqlanywhere/externalenvironments/externc/serverside.sql
rm -f samples/sqlanywhere/externalenvironments/externc/serversideesql.sqc
rm -f samples/sqlanywhere/externalenvironments/externc/serversideodbc.cpp
rm -f samples/sqlanywhere/externalenvironments/externc/testsrc.cpp
rm -f samples/sqlanywhere/externalenvironments/externc/testsrc.h
rm -f samples/sqlanywhere/externalenvironments/perl/datatype.pl
rm -f samples/sqlanywhere/externalenvironments/perl/datatype.sql
rm -f samples/sqlanywhere/externalenvironments/perl/serverside.pl
rm -f samples/sqlanywhere/externalenvironments/perl/serverside.sql
rm -f samples/sqlanywhere/externallibrariesfulltext/build.sh
rm -f samples/sqlanywhere/externallibrariesfulltext/clean.sh
rm -f samples/sqlanywhere/externallibrariesfulltext/pf_sample.cpp
rm -f samples/sqlanywhere/externallibrariesfulltext/pf_sample.sql
rm -f samples/sqlanywhere/externallibrariesfulltext/pf_sample_tests.sql
rm -f samples/sqlanywhere/externallibrariesfulltext/readme.txt
rm -f samples/sqlanywhere/externallibrariesfulltext/readme_ja.txt
rm -f samples/sqlanywhere/externallibrariesfulltext/show_exports.sh
rm -f samples/sqlanywhere/externallibrariesfulltext/tb_sample.cpp
rm -f samples/sqlanywhere/externallibrariesfulltext/tb_sample.sql
rm -f samples/sqlanywhere/externallibrariesfulltext/tb_sample_tests.sql
rm -f samples/sqlanywhere/externalprocedures/build.sh
rm -f samples/sqlanywhere/externalprocedures/clean.sh
rm -f samples/sqlanywhere/externalprocedures/extproc.cpp
rm -f samples/sqlanywhere/externalprocedures/extproc.sql
rm -f samples/sqlanywhere/externalprocedures/readme.txt
rm -f samples/sqlanywhere/externalprocedures/readme_ja.txt
rm -f samples/sqlanywhere/externalprocedures/show_exports.sh
rm -f samples/sqlanywhere/externalprocedures/tests.sql
rm -f samples/sqlanywhere/http/cookie.sql
rm -f samples/sqlanywhere/http/gallery.sql
rm -f samples/sqlanywhere/http/globalweather.wsdl
rm -f samples/sqlanywhere/http/gov.weather.wsdl
rm -f samples/sqlanywhere/http/html_cal_test.sql
rm -f samples/sqlanywhere/http/html_calendar.sql
rm -f samples/sqlanywhere/http/html_select.sql
rm -f samples/sqlanywhere/http/image_readfile.sql
rm -f samples/sqlanywhere/http/json_sample.sql
rm -f samples/sqlanywhere/http/picture.jpg
rm -f samples/sqlanywhere/http/post_data.sql
rm -f samples/sqlanywhere/http/put_data.sql
rm -f samples/sqlanywhere/http/readme.txt
rm -f samples/sqlanywhere/http/session.sql
rm -f samples/sqlanywhere/http/show_request_info.sql
rm -f samples/sqlanywhere/http/show_table.sql
rm -f samples/sqlanywhere/http/soap.globalweather.sql
rm -f samples/sqlanywhere/http/soap.gov.weather.sql
rm -f samples/sqlanywhere/http/soapsession.sql
rm -f samples/sqlanywhere/http/test_request_db.sql
rm -f samples/sqlanywhere/javainvoice/Invoice.java
rm -f samples/sqlanywhere/javainvoice/build.sh
rm -f samples/sqlanywhere/javainvoice/clean.sh
rm -f samples/sqlanywhere/javainvoice/install.sql
rm -f samples/sqlanywhere/javainvoice/readme.txt
rm -f samples/sqlanywhere/javainvoice/readme_ja.txt
rm -f samples/sqlanywhere/javainvoice/remove.sql
rm -f samples/sqlanywhere/javainvoice/run.sh
rm -f samples/sqlanywhere/javainvoice/run.sql
rm -f samples/sqlanywhere/odatasecurity/SecureView.java
rm -f samples/sqlanywhere/odatasecurity/build.sh
rm -f samples/sqlanywhere/odatasecurity/clean.sh
rm -f samples/sqlanywhere/odatasecurity/init.sql
rm -f samples/sqlanywhere/odatasecurity/keystore.jks
rm -f samples/sqlanywhere/odatasecurity/readme.txt
rm -f samples/sqlanywhere/odatasecurity/run.sh
rm -f samples/sqlanywhere/odatasecurity/start_server.sh
rm -f samples/sqlanywhere/odatasecurity/stop_server.sh
rm -f samples/sqlanywhere/oemstring/build.sh
rm -f samples/sqlanywhere/oemstring/clean.sh
rm -f samples/sqlanywhere/oemstring/dboem.cpp
rm -f samples/sqlanywhere/oemstring/dboem.pl
rm -f samples/sqlanywhere/oemstring/readme.txt
rm -f samples/sqlanywhere/oemstring/readme_ja.txt
rm -f samples/sqlanywhere/performancefetch/build.sh
rm -f samples/sqlanywhere/performancefetch/clean.sh
rm -f samples/sqlanywhere/performancefetch/fetchtst.sqc
rm -f samples/sqlanywhere/performancefetch/odbcfet.c
rm -f samples/sqlanywhere/performancefetch/readme.txt
rm -f samples/sqlanywhere/performanceinsert/build.sh
rm -f samples/sqlanywhere/performanceinsert/clean.sh
rm -f samples/sqlanywhere/performanceinsert/instest.sqc
rm -f samples/sqlanywhere/performanceinsert/readme.txt
rm -f samples/sqlanywhere/performancetracetime/readme.txt
rm -f samples/sqlanywhere/performancetracetime/readme_ja.txt
rm -f samples/sqlanywhere/performancetracetime/tracetime.pl
rm -f samples/sqlanywhere/performancetransaction/build.sh
rm -f samples/sqlanywhere/performancetransaction/clean.sh
rm -f samples/sqlanywhere/performancetransaction/esqltran.sqc
rm -f samples/sqlanywhere/performancetransaction/odbctran.cpp
rm -f samples/sqlanywhere/performancetransaction/readme.txt
rm -f samples/sqlanywhere/performancetransaction/trantabs.sql
rm -f samples/sqlanywhere/performancetransaction/trantest.cpp
rm -f samples/sqlanywhere/performancetransaction/trantest.hpp
rm -f samples/sqlanywhere/performancetransaction/tranthrd.cpp
rm -f samples/sqlanywhere/performancetransaction/tranthrd.hpp
rm -f samples/sqlanywhere/performancetransaction/worklist.cpp
rm -f samples/sqlanywhere/sql/create_default_stoplist.sql
rm -f samples/sqlanywhere/sql/readme.txt
rm -f samples/sqlanywhere/sql/readme_ja.txt
rm -f samples/sqlanywhere/sql/sa_get_column_list.sql
rm -f samples/sqlanywhere/sql/simplify_geometry.sql
rm -f samples/sqlanywhere/sql/stopword_language.csv
rm -f samples/sqlanywhere/sql/stopword_table.csv
rm -f samples/sqlanywhere/sql/verify_password.sql
rm -f samples/start_mobilink_qanywhere_sample32.sh
rm -f samples/start_mobilink_qanywhere_sample64.sh
rm -f samples/ultralite/custdb/custdb.db
rm -f samples/ultralite/custdb/custdb.h
rm -f samples/ultralite/custdb/custdb.sql
rm -f samples/ultralite/custdb/custdb.udb
rm -f samples/ultralite/custdb/custdbcpp.cpp
rm -f samples/ultralite/custdb/grant.sql
rm -f samples/ultralite/custdb/linux/build.sh
rm -f samples/ultralite/custdb/linux/custio.c
rm -f samples/ultralite/custdb/linux/mobilink.sh
rm -f samples/ultralite/custdb/makedbs.sh
rm -f samples/ultralite/custdb/platform.h
rm -f samples/ultralite/custdb/readme.txt
rm -f samples/ultralite/starter/build.sh
rm -f samples/ultralite/starter/readme.txt
rm -f samples/ultralite/starter/ulsample.cpp
rm -f scripts/adata/ClothVisor.jpg
rm -f scripts/adata/CottonCap.jpg
rm -f scripts/adata/CottonShorts.jpg
rm -f scripts/adata/CrewNeck.jpg
rm -f scripts/adata/HoodedSweatshirt.jpg
rm -f scripts/adata/PlasticVisor.jpg
rm -f scripts/adata/TankTop.jpg
rm -f scripts/adata/V-Neck.jpg
rm -f scripts/adata/WoolCap.jpg
rm -f scripts/adata/ZippedSweatshirt.jpg
rm -f scripts/adata/contact.sql
rm -f scripts/adata/customer.sql
rm -f scripts/adata/dept.sql
rm -f scripts/adata/employee.sql
rm -f scripts/adata/fin_code.sql
rm -f scripts/adata/fin_data.sql
rm -f scripts/adata/marketinfo.sql
rm -f scripts/adata/product.sql
rm -f scripts/adata/sales_o.sql
rm -f scripts/adata/sales_oi.sql
rm -f scripts/adata/stcontacts.sql
rm -f scripts/adata/stshapes.sql
rm -f scripts/mkdemo.sql
rm -f scripts/optdeflt.sql
rm -f scripts/opttemp.sql
rm -f scripts/salespub.sql
rm -f scripts/st_geometry_config.tgz
rm -f scripts/unloadold.sql
rm -f scripts/use_old_dbextf.sql
rm -f sdk/c/sacapidll.c
rm -f sdk/c/sqlcadat.c
rm -f sdk/dbcapi/examples/build.sh
rm -f sdk/dbcapi/examples/callback.cpp
rm -f sdk/dbcapi/examples/connecting.cpp
rm -f sdk/dbcapi/examples/dbcapi_isql.cpp
rm -f sdk/dbcapi/examples/fetching_a_result_set.cpp
rm -f sdk/dbcapi/examples/fetching_multiple_from_sp.cpp
rm -f sdk/dbcapi/examples/preparing_statements.cpp
rm -f sdk/dbcapi/examples/send_retrieve_full_blob.cpp
rm -f sdk/dbcapi/examples/send_retrieve_part_blob.cpp
rm -f sdk/dbcapi/examples/stmt_exec.cpp
rm -f sdk/dbcapi/examples/stmt_reset.cpp
rm -f sdk/dbcapi/sacapi.h
rm -f sdk/dbcapi/sacapidll.c
rm -f sdk/dbcapi/sacapidll.h
rm -f sdk/include/dbmlsynccli.h
rm -f sdk/include/dbrmt.h
rm -f sdk/include/dbtlvers.h
rm -f sdk/include/dbtools.h
rm -f sdk/include/dllapi.h
rm -f sdk/include/extfnapi.h
rm -f sdk/include/extfncmn.h
rm -f sdk/include/extpfapiv1.h
rm -f sdk/include/exttbapiv1.h
rm -f sdk/include/exttxtcmn.h
rm -f sdk/include/imlreplayapicallbacks.hpp
rm -f sdk/include/imlreplayrow.hpp
rm -f sdk/include/imlreplayuploadtable.hpp
rm -f sdk/include/imlreplayuploadtransaction.hpp
rm -f sdk/include/lictype.h
rm -f sdk/include/mlfiletransfer.h
rm -f sdk/include/mlreplayapi.hpp
rm -f sdk/include/mlreplaycallbacks.hpp
rm -f sdk/include/mlreplaycvector.hpp
rm -f sdk/include/odbc.h
rm -f sdk/include/poppk.h
rm -f sdk/include/pshpk1.h
rm -f sdk/include/pshpk2.h
rm -f sdk/include/pshpk4.h
rm -f sdk/include/sacapi.h
rm -f sdk/include/sacapidll.h
rm -f sdk/include/saci.h
rm -f sdk/include/saciloader.h
rm -f sdk/include/saodbc.h
rm -f sdk/include/sqlca.h
rm -f sdk/include/sqlcallback.h
rm -f sdk/include/sqlda.h
rm -f sdk/include/sqldef.h
rm -f sdk/include/sqlerr.h
rm -f sdk/include/sqlfuncs.h
rm -f sdk/include/sqlhosttype.h
rm -f sdk/include/sqlos.h
rm -f sdk/include/sqlstate.h
rm -f sdk/include/sqltype.h
rm -f sdk/include/sserror.h
rm -f sdk/include/ulcpp.h
rm -f sdk/include/uldef.h
rm -f sdk/include/ulglobal.h
rm -f sdk/include/ulprotos.h
rm -f sdk/include/ulsqlfuncs.h
rm -f sdk/include/ulsynchelper.h
rm -f sdk/include/unixodbc.h
rm -f sdk/perl/Changes
rm -f sdk/perl/MANIFEST
rm -f sdk/perl/Makefile.PL
rm -f sdk/perl/README
rm -f sdk/perl/README.NT
rm -f sdk/perl/SQLAnywhere.h
rm -f sdk/perl/SQLAnywhere.pm
rm -f sdk/perl/SQLAnywhere.xs
rm -f sdk/perl/dbdimp.c
rm -f sdk/perl/dbdimp.h
rm -f sdk/perl/dolink.pl
rm -f sdk/perl/eg/blobs.pl
rm -f sdk/perl/eg/connect.pl
rm -f sdk/perl/eg/retrieve.pl
rm -f sdk/perl/lib/DBD/SQLAnywhere/GetInfo.pm
rm -f sdk/perl/license.txt
rm -f sdk/perl/sacapi.h
rm -f sdk/perl/sacapidll.c
rm -f sdk/perl/sacapidll.h
rm -f sdk/perl/sqlerr.h
rm -f sdk/perl/t/base.t
rm -f sdk/perl/t/login.t
rm -f sdk/perl/t/main.t
rm -f sdk/perl/t/place.t
rm -f sdk/perlenv/Makefile.PL
rm -f sdk/perlenv/SAExtEnvIO.pm
rm -f sdk/perlenv/SAPerlGlue.pm
rm -f sdk/perlenv/consts.h
rm -f sdk/perlenv/dolink.pl
rm -f sdk/perlenv/extenv.h
rm -f sdk/perlenv/langload.h
rm -f sdk/perlenv/perlglue.xs
rm -f sdk/php/Changes
rm -f sdk/php/config.m4
rm -f sdk/php/config.w32
rm -f sdk/php/examples/SAP_logo.gif
rm -f sdk/php/examples/blob.php
rm -f sdk/php/examples/connect.php
rm -f sdk/php/examples/details.php
rm -f sdk/php/examples/error_handling.php
rm -f sdk/php/examples/fetch.php
rm -f sdk/php/examples/fetch_assoc.php
rm -f sdk/php/examples/fetch_object.php
rm -f sdk/php/examples/image-insert.php
rm -f sdk/php/examples/image-retrieve.php
rm -f sdk/php/examples/master.php
rm -f sdk/php/examples/nested.php
rm -f sdk/php/examples/nested_use_result.php
rm -f sdk/php/examples/query.php
rm -f sdk/php/examples/resultall.php
rm -f sdk/php/examples/resultalljs.php
rm -f sdk/php/examples/resultallperf.php
rm -f sdk/php/examples/stmt_insert.php
rm -f sdk/php/examples/stored_proc.php
rm -f sdk/php/examples/test.php
rm -f sdk/php/examples/transactions.php
rm -f sdk/php/examples/webisql.php
rm -f sdk/php/examples/webisql_using_extensions.php
rm -f sdk/php/license.txt
rm -f sdk/php/php_sqlany_ver.h
rm -f sdk/php/php_sqlanywhere.h
rm -f sdk/php/sacapi.h
rm -f sdk/php/sacapidll.c
rm -f sdk/php/sacapidll.h
rm -f sdk/php/sqlany_dbg.c
rm -f sdk/php/sqlany_dbg.h
rm -f sdk/php/sqlanywhere.c
rm -f sdk/phpenv/config.m4
rm -f sdk/phpenv/consts.h
rm -f sdk/phpenv/extenv.h
rm -f sdk/phpenv/langload.h
rm -f sdk/phpenv/php_sqlanywhere_extenv.h
rm -f sdk/phpenv/sqlanywhere_extenv.c
rm -f sdk/python/README.rst
rm -f sdk/python/scripts/dbapi20.py
rm -f sdk/python/scripts/runtests.py
rm -f sdk/python/scripts/test.py
rm -f sdk/python/scripts/test_sqlanydb_ext.py
rm -f sdk/python/setup.py
rm -f sdk/python/sqlanydb.py
rm -f sdk/ruby/README
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/CHANGELOG
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/LICENSE
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/README
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/Rakefile
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/lib/active_record/connection_adapters/sqlanywhere_adapter.rb
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/test/connection.rb
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/test/sqlanywhere.drop.sql
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/test/sqlanywhere.sql
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/test/sqlanywhere2.drop.sql
rm -f sdk/ruby/activerecord-sqlanywhere-adapter/test/sqlanywhere2.sql
rm -f sdk/ruby/dbd-sqlanywhere/CHANGELOG
rm -f sdk/ruby/dbd-sqlanywhere/LICENSE
rm -f sdk/ruby/dbd-sqlanywhere/README
rm -f sdk/ruby/dbd-sqlanywhere/Rakefile
rm -f sdk/ruby/dbd-sqlanywhere/lib/dbd/SQLAnywhere.rb
rm -f sdk/ruby/dbd-sqlanywhere/lib/dbd/sqlanywhere/database.rb
rm -f sdk/ruby/dbd-sqlanywhere/lib/dbd/sqlanywhere/driver.rb
rm -f sdk/ruby/dbd-sqlanywhere/lib/dbd/sqlanywhere/statement.rb
rm -f sdk/ruby/dbd-sqlanywhere/test/dbd/sqlanywhere/base.rb
rm -f sdk/ruby/dbd-sqlanywhere/test/dbd/sqlanywhere/down.sql
rm -f sdk/ruby/dbd-sqlanywhere/test/dbd/sqlanywhere/up.sql
rm -f sdk/ruby/sqlanywhere/CHANGELOG
rm -f sdk/ruby/sqlanywhere/LICENSE
rm -f sdk/ruby/sqlanywhere/README
rm -f sdk/ruby/sqlanywhere/Rakefile
rm -f sdk/ruby/sqlanywhere/ext/extconf.rb
rm -f sdk/ruby/sqlanywhere/ext/sacapi.h
rm -f sdk/ruby/sqlanywhere/ext/sacapidll.c
rm -f sdk/ruby/sqlanywhere/ext/sacapidll.h
rm -f sdk/ruby/sqlanywhere/ext/sqlanywhere.c
rm -f sdk/ruby/sqlanywhere/test/sqlanywhere_test.rb
rm -f sdk/ruby/sqlanywhere/test/test.sql
rm -f selinux/README
rm -f selinux/buildfc.sh
rm -f selinux/sqlanywhere.fct
rm -f selinux/sqlanywhere.if
rm -f selinux/sqlanywhere.te
rm -f sqlacockpit.template
rm -f support/de/OnlineResources.html
rm -f support/de/updchk.html
rm -f support/en/OnlineResources.html
rm -f support/en/updchk.html
rm -f support/fr/OnlineResources.html
rm -f support/fr/updchk.html
rm -f support/ja/OnlineResources.html
rm -f support/ja/updchk.html
rm -f support/zh/OnlineResources.html
rm -f support/zh/updchk.html
rm -f thirdpartylegal/SQLAnywhere17ThirdPartyLegal.pdf
rm -f thirdpartylegal/SQLAnywhere17ThirdPartyLegal.txt
rm -f tix/default.tix
rm -f ultralite/linux/x64/lib/libulbase.a
rm -f ultralite/linux/x64/lib/libulrsa.a
rm -f ultralite/linux/x64/lib/libulrt.a
rm -f ultralite/linux/x86/lib/libulbase.a
rm -f ultralite/linux/x86/lib/libulrsa.a
rm -f ultralite/linux/x86/lib/libulrt.a
rm -f upgrade_*.log
rm -f vcsagent/sadatabase/SADatabase.xml
rm -f vcsagent/sadatabase/SADatabaseTypes.cf
rm -f vcsagent/sadatabase/clean.pl
rm -f vcsagent/sadatabase/monitor.pl
rm -f vcsagent/sadatabase/offline.pl
rm -f vcsagent/sadatabase/online.pl
rm -f vcsagent/saserver/SAServer.xml
rm -f vcsagent/saserver/SAServerTypes.cf
rm -f vcsagent/saserver/clean.pl
rm -f vcsagent/saserver/monitor.pl
rm -f vcsagent/saserver/offline.pl
rm -f vcsagent/saserver/online.pl
rm -rf documentation
rm -rf openserver
rm -rf sa_help_launcher
rm -rf sun
rm -rf "$HOME/sa_help_launcher" >/dev/null 2>&1
rm -rf "$HOME/.sqlanywhere17" >/dev/null 2>&1
rm -rf bin32/jre180/lib/fonts/fallback >/dev/null 2>&1
rmdir -p bin32/jre180/lib/fonts >/dev/null 2>&1
rm -rf bin64/jre180/lib/fonts/fallback >/dev/null 2>&1
rmdir -p bin64/jre180/lib/fonts >/dev/null 2>&1
rmdir vcsagent/saserver 2>/dev/null
rmdir vcsagent/sadatabase 2>/dev/null
rmdir vcsagent 2>/dev/null
rmdir ultralite/linux/x86/lib 2>/dev/null
rmdir ultralite/linux/x86 2>/dev/null
rmdir ultralite/linux/x64/lib 2>/dev/null
rmdir ultralite/linux/x64 2>/dev/null
rmdir ultralite/linux 2>/dev/null
rmdir ultralite 2>/dev/null
rmdir tix 2>/dev/null
rmdir thirdpartylegal 2>/dev/null
rmdir support/zh 2>/dev/null
rmdir support/ja 2>/dev/null
rmdir support/fr 2>/dev/null
rmdir support/en 2>/dev/null
rmdir support/de 2>/dev/null
rmdir support 2>/dev/null
rmdir selinux 2>/dev/null
rmdir sdk/ruby/sqlanywhere/test 2>/dev/null
rmdir sdk/ruby/sqlanywhere/ext 2>/dev/null
rmdir sdk/ruby/sqlanywhere 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/test/dbd/sqlanywhere 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/test/dbd 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/test 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/lib/dbd/sqlanywhere 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/lib/dbd 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere/lib 2>/dev/null
rmdir sdk/ruby/dbd-sqlanywhere 2>/dev/null
rmdir sdk/ruby/activerecord-sqlanywhere-adapter/test 2>/dev/null
rmdir sdk/ruby/activerecord-sqlanywhere-adapter/lib/active_record/connection_adapters 2>/dev/null
rmdir sdk/ruby/activerecord-sqlanywhere-adapter/lib/active_record 2>/dev/null
rmdir sdk/ruby/activerecord-sqlanywhere-adapter/lib 2>/dev/null
rmdir sdk/ruby/activerecord-sqlanywhere-adapter 2>/dev/null
rmdir sdk/ruby 2>/dev/null
rmdir sdk/python/scripts 2>/dev/null
rmdir sdk/python 2>/dev/null
rmdir sdk/phpenv 2>/dev/null
rmdir sdk/php/examples 2>/dev/null
rmdir sdk/php 2>/dev/null
rmdir sdk/perlenv 2>/dev/null
rmdir sdk/perl/t 2>/dev/null
rmdir sdk/perl/lib/DBD/SQLAnywhere 2>/dev/null
rmdir sdk/perl/lib/DBD 2>/dev/null
rmdir sdk/perl/lib 2>/dev/null
rmdir sdk/perl/eg 2>/dev/null
rmdir sdk/perl 2>/dev/null
rmdir sdk/include 2>/dev/null
rmdir sdk/dbcapi/examples 2>/dev/null
rmdir sdk/dbcapi 2>/dev/null
rmdir sdk/c 2>/dev/null
rmdir sdk 2>/dev/null
rmdir scripts/adata 2>/dev/null
rmdir scripts 2>/dev/null
rmdir samples/ultralite/starter 2>/dev/null
rmdir samples/ultralite/custdb/linux 2>/dev/null
rmdir samples/ultralite/custdb 2>/dev/null
rmdir samples/ultralite 2>/dev/null
rmdir samples/sqlanywhere/sql 2>/dev/null
rmdir samples/sqlanywhere/performancetransaction 2>/dev/null
rmdir samples/sqlanywhere/performancetracetime 2>/dev/null
rmdir samples/sqlanywhere/performanceinsert 2>/dev/null
rmdir samples/sqlanywhere/performancefetch 2>/dev/null
rmdir samples/sqlanywhere/oemstring 2>/dev/null
rmdir samples/sqlanywhere/odatasecurity 2>/dev/null
rmdir samples/sqlanywhere/javainvoice 2>/dev/null
rmdir samples/sqlanywhere/http 2>/dev/null
rmdir samples/sqlanywhere/externalprocedures 2>/dev/null
rmdir samples/sqlanywhere/externallibrariesfulltext 2>/dev/null
rmdir samples/sqlanywhere/externalenvironments/perl 2>/dev/null
rmdir samples/sqlanywhere/externalenvironments/externc 2>/dev/null
rmdir samples/sqlanywhere/externalenvironments 2>/dev/null
rmdir samples/sqlanywhere/diskfull 2>/dev/null
rmdir samples/sqlanywhere/dbtools 2>/dev/null
rmdir samples/sqlanywhere/c 2>/dev/null
rmdir samples/sqlanywhere 2>/dev/null
rmdir samples/mobilink/partitioning 2>/dev/null
rmdir samples/mobilink/mltemplate/template/mobilink/rdb/sqla/test 2>/dev/null
rmdir samples/mobilink/mltemplate/template/mobilink/rdb/sqla 2>/dev/null
rmdir samples/mobilink/mltemplate/template/mobilink/rdb 2>/dev/null
rmdir samples/mobilink/mltemplate/template/mobilink/cdb/sqla/test 2>/dev/null
rmdir samples/mobilink/mltemplate/template/mobilink/cdb/sqla/basic 2>/dev/null
rmdir samples/mobilink/mltemplate/template/mobilink/cdb/sqla 2>/dev/null
rmdir samples/mobilink/mltemplate/template/mobilink/cdb 2>/dev/null
rmdir samples/mobilink/mltemplate/template/mobilink 2>/dev/null
rmdir samples/mobilink/mltemplate/template 2>/dev/null
rmdir samples/mobilink/mltemplate/helper 2>/dev/null
rmdir samples/mobilink/mltemplate 2>/dev/null
rmdir samples/mobilink/mlreplay 2>/dev/null
rmdir samples/mobilink/java_authentication 2>/dev/null
rmdir samples/mobilink/globalautoincrement 2>/dev/null
rmdir samples/mobilink/custdb 2>/dev/null
rmdir samples/mobilink/contact 2>/dev/null
rmdir samples/mobilink 2>/dev/null
rmdir samples/certificates 2>/dev/null
rmdir samples 2>/dev/null
rmdir res 2>/dev/null
rmdir relayserver/quicksetup_apache 2>/dev/null
rmdir relayserver/apache24/bin64s 2>/dev/null
rmdir relayserver/apache24/bin64 2>/dev/null
rmdir relayserver/apache24 2>/dev/null
rmdir relayserver/apache22/bin64s 2>/dev/null
rmdir relayserver/apache22/bin64 2>/dev/null
rmdir relayserver/apache22 2>/dev/null
rmdir relayserver 2>/dev/null
rmdir node/sqlanywhere_jsextenv/lib 2>/dev/null
rmdir node/sqlanywhere_jsextenv/bin64s 2>/dev/null
rmdir node/sqlanywhere_jsextenv/bin64 2>/dev/null
rmdir node/sqlanywhere_jsextenv/bin32s 2>/dev/null
rmdir node/sqlanywhere_jsextenv/bin32 2>/dev/null
rmdir node/sqlanywhere_jsextenv 2>/dev/null
rmdir node/sqlanywhere-xs/lib 2>/dev/null
rmdir node/sqlanywhere-xs/bin64s 2>/dev/null
rmdir node/sqlanywhere-xs/bin64 2>/dev/null
rmdir node/sqlanywhere-xs/bin32s 2>/dev/null
rmdir node/sqlanywhere-xs/bin32 2>/dev/null
rmdir node/sqlanywhere-xs 2>/dev/null
rmdir node 2>/dev/null
rmdir mobilink/upgrade/9.0.2 2>/dev/null
rmdir mobilink/upgrade/9.0.1 2>/dev/null
rmdir mobilink/upgrade/9.0.0 2>/dev/null
rmdir mobilink/upgrade/8.0.x 2>/dev/null
rmdir mobilink/upgrade/8.0.1 2>/dev/null
rmdir mobilink/upgrade/8.0.0 2>/dev/null
rmdir mobilink/upgrade/7.0.x 2>/dev/null
rmdir mobilink/upgrade/17.0.0 2>/dev/null
rmdir mobilink/upgrade/16.0.0 2>/dev/null
rmdir mobilink/upgrade/12.0.1 2>/dev/null
rmdir mobilink/upgrade/12.0.0 2>/dev/null
rmdir mobilink/upgrade/11.0.x 2>/dev/null
rmdir mobilink/upgrade/10.0.x 2>/dev/null
rmdir mobilink/upgrade 2>/dev/null
rmdir mobilink/setup 2>/dev/null
rmdir mobilink/mltemplate/templates/consdb/sqla 2>/dev/null
rmdir mobilink/mltemplate/templates/consdb/hana 2>/dev/null
rmdir mobilink/mltemplate/templates/consdb 2>/dev/null
rmdir mobilink/mltemplate/templates 2>/dev/null
rmdir mobilink/mltemplate/javascript 2>/dev/null
rmdir mobilink/mltemplate/helpers 2>/dev/null
rmdir mobilink/mltemplate 2>/dev/null
rmdir mobilink 2>/dev/null
rmdir lib64 2>/dev/null
rmdir lib32 2>/dev/null
rmdir java 2>/dev/null
rmdir deployment/res/scripts 2>/dev/null
rmdir deployment/res/language/zh 2>/dev/null
rmdir deployment/res/language/ja 2>/dev/null
rmdir deployment/res/language/fr 2>/dev/null
rmdir deployment/res/language/en 2>/dev/null
rmdir deployment/res/language/de 2>/dev/null
rmdir deployment/res/language 2>/dev/null
rmdir deployment/res 2>/dev/null
rmdir deployment/lib64 2>/dev/null
rmdir deployment/lib32 2>/dev/null
rmdir deployment/bin64s 2>/dev/null
rmdir deployment/bin64 2>/dev/null
rmdir deployment/bin32s 2>/dev/null
rmdir deployment/bin32 2>/dev/null
rmdir deployment 2>/dev/null
rmdir collate/unicode 2>/dev/null
rmdir collate 2>/dev/null
rmdir charsets/unicode 2>/dev/null
rmdir charsets 2>/dev/null
rmdir bin64s/language/zh 2>/dev/null
rmdir bin64s/language/ja 2>/dev/null
rmdir bin64s/language/fr 2>/dev/null
rmdir bin64s/language/en 2>/dev/null
rmdir bin64s/language/de 2>/dev/null
rmdir bin64s/language 2>/dev/null
rmdir bin64s/jre180/lib/security/policy/unlimited 2>/dev/null
rmdir bin64s/jre180/lib/security/policy/limited 2>/dev/null
rmdir bin64s/jre180/lib/security/policy 2>/dev/null
rmdir bin64s/jre180/lib/security 2>/dev/null
rmdir bin64s/jre180/lib/oblique-fonts 2>/dev/null
rmdir bin64s/jre180/lib/management 2>/dev/null
rmdir bin64s/jre180/lib/images/cursors 2>/dev/null
rmdir bin64s/jre180/lib/images 2>/dev/null
rmdir bin64s/jre180/lib/fonts 2>/dev/null
rmdir bin64s/jre180/lib/ext 2>/dev/null
rmdir bin64s/jre180/lib/cmm 2>/dev/null
rmdir bin64s/jre180/lib/amd64/server 2>/dev/null
rmdir bin64s/jre180/lib/amd64/jli 2>/dev/null
rmdir bin64s/jre180/lib/amd64 2>/dev/null
rmdir bin64s/jre180/lib 2>/dev/null
rmdir bin64s/jre180/bin 2>/dev/null
rmdir bin64s/jre180 2>/dev/null
rmdir bin64s/dbsvc_scripts 2>/dev/null
rmdir bin64s 2>/dev/null
rmdir bin64/language/zh 2>/dev/null
rmdir bin64/language/ja 2>/dev/null
rmdir bin64/language/fr 2>/dev/null
rmdir bin64/language/en 2>/dev/null
rmdir bin64/language/de 2>/dev/null
rmdir bin64/language 2>/dev/null
rmdir bin64/jre180/lib/security/policy/unlimited 2>/dev/null
rmdir bin64/jre180/lib/security/policy/limited 2>/dev/null
rmdir bin64/jre180/lib/security/policy 2>/dev/null
rmdir bin64/jre180/lib/security 2>/dev/null
rmdir bin64/jre180/lib/oblique-fonts 2>/dev/null
rmdir bin64/jre180/lib/management 2>/dev/null
rmdir bin64/jre180/lib/images/cursors 2>/dev/null
rmdir bin64/jre180/lib/images 2>/dev/null
rmdir bin64/jre180/lib/fonts 2>/dev/null
rmdir bin64/jre180/lib/ext 2>/dev/null
rmdir bin64/jre180/lib/cmm 2>/dev/null
rmdir bin64/jre180/lib/amd64/server 2>/dev/null
rmdir bin64/jre180/lib/amd64/jli 2>/dev/null
rmdir bin64/jre180/lib/amd64 2>/dev/null
rmdir bin64/jre180/lib 2>/dev/null
rmdir bin64/jre180/bin 2>/dev/null
rmdir bin64/jre180 2>/dev/null
rmdir bin64/dbsvc_scripts 2>/dev/null
rmdir bin64 2>/dev/null
rmdir bin32s/language/zh 2>/dev/null
rmdir bin32s/language/ja 2>/dev/null
rmdir bin32s/language/fr 2>/dev/null
rmdir bin32s/language/en 2>/dev/null
rmdir bin32s/language/de 2>/dev/null
rmdir bin32s/language 2>/dev/null
rmdir bin32s/dbsvc_scripts 2>/dev/null
rmdir bin32s 2>/dev/null
rmdir bin32/language/zh 2>/dev/null
rmdir bin32/language/ja 2>/dev/null
rmdir bin32/language/fr 2>/dev/null
rmdir bin32/language/en 2>/dev/null
rmdir bin32/language/de 2>/dev/null
rmdir bin32/language 2>/dev/null
rmdir bin32/dbsvc_scripts 2>/dev/null
rmdir bin32 2>/dev/null
LO=`find "$SAROOT" -type f 2>/dev/null | grep -v uninstall.sh`
[ "$LO" = "" ] && rm -f uninstall.sh

rm -f /usr/share/applications/ianywhere-17* 2>/dev/null
rm -f /usr/share/desktop-directories/ianywhere-17* 2>/dev/null
rm -f /etc/xdg/menus/applications-merged/ianywhere-17* 2>/dev/null
rm -f "$HOME"/.local/share/applications/ianywhere-17* 2>/dev/null
rm -f "$HOME"/.local/share/desktop-directories/ianywhere-17* 2>/dev/null
rm -f "$HOME"/.config/menus/applications-merged/ianywhere-17* 2>/dev/null

test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" && . "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
rm -f "${XDG_DESKTOP_DIR:-$HOME/Desktop}"/ianywhere-17* 2>/dev/null
cd /tmp
rmdir "$SAROOT" 2>/dev/null
[ -r "$OPWD" ] && cd "$OPWD"
