#!/bin/sh 

# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.

svc_t_init()
############
{
    NOOP=NOOP
}

svc_t_displayname()
###################
{
    echo "RSOE"
}

svc_t_toolname()
################
{
    echo "rsoe2"
}

svc_t_toolspath()
#################
# can look at $BITNESS, $BIN32, etc. here to override bitness
# 's' path is the script or shortcut path for this tool
{
    echo $SQLANYDIR/${BIN}s/`svc_t_toolname`
}

svc_t_toolpath()
################
# can look at $BITNESS, $BIN32, etc. here to override bitness
{
    echo $SQLANYDIR/$BIN/`svc_t_toolname`
}

svc_t_process_cmdline()
#######################
# in: name of an output array variable in which to put the command line
# in: command line arguments
# out: store command line as array in variable provided 
# out: add -ud if not already there
{
    svc_t_process_cmdline_add_ud "${@}"
}

